"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from pipeshub_sdk.errors import PipeshubError
from pipeshub_sdk.types import BaseModel
from typing import Optional


class ResetPasswordBadRequestErrorData(BaseModel):
    error: Optional[str] = None


@dataclass(unsafe_hash=True)
class ResetPasswordBadRequestError(PipeshubError):
    r"""Invalid current password or weak new password"""

    data: ResetPasswordBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: ResetPasswordBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
