"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from pipeshub_sdk.errors import PipeshubError
from pipeshub_sdk.types import BaseModel
from typing import Optional


class UnauthorizedErrorData(BaseModel):
    error: Optional[str] = None


@dataclass(unsafe_hash=True)
class UnauthorizedError(PipeshubError):
    r"""SAML authentication failed"""

    data: UnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: UnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class SamlSignInCallbackBadRequestErrorData(BaseModel):
    error: Optional[str] = None


@dataclass(unsafe_hash=True)
class SamlSignInCallbackBadRequestError(PipeshubError):
    r"""Invalid SAML response"""

    data: SamlSignInCallbackBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: SamlSignInCallbackBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
