"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addmessagerequest import AddMessageRequest, AddMessageRequestTypedDict
from pipeshub.types import BaseModel
from pipeshub.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class AddAgentMessageRequestTypedDict(TypedDict):
    agent_key: str
    conversation_id: str
    body: AddMessageRequestTypedDict
    r"""Request payload"""


class AddAgentMessageRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        AddMessageRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""
