"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authstep import AuthStep, AuthStepTypedDict
from pipeshub.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class AuthConfigTypedDict(TypedDict):
    r"""Organization authentication configuration. Supports 1-3 authentication steps for multi-factor authentication.
    **Validation Rules:**
    - Minimum 1 step, maximum 3 steps
    - Each step must have unique order
    - No duplicate methods within the same step
    - No method can appear in multiple steps

    """

    auth_methods: List[AuthStepTypedDict]
    r"""List of authentication steps in order"""


class AuthConfig(BaseModel):
    r"""Organization authentication configuration. Supports 1-3 authentication steps for multi-factor authentication.
    **Validation Rules:**
    - Minimum 1 step, maximum 3 steps
    - Each step must have unique order
    - No duplicate methods within the same step
    - No method can appear in multiple steps

    """

    auth_methods: Annotated[List[AuthStep], pydantic.Field(alias="authMethods")]
    r"""List of authentication steps in order"""


try:
    AuthConfig.model_rebuild()
except NameError:
    pass
