"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, SecurityMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CheckPasswordStatusSecurityTypedDict(TypedDict):
    scoped_token: str


class CheckPasswordStatusSecurity(BaseModel):
    scoped_token: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ]


class CheckPasswordStatusResponseTypedDict(TypedDict):
    r"""Password status retrieved"""

    has_password: NotRequired[bool]
    r"""Whether the user has a password set"""


class CheckPasswordStatusResponse(BaseModel):
    r"""Password status retrieved"""

    has_password: Annotated[Optional[bool], pydantic.Field(alias="hasPassword")] = None
    r"""Whether the user has a password set"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["hasPassword"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CheckPasswordStatusResponse.model_rebuild()
except NameError:
    pass
