"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import UnrecognizedStr
from typing import Literal, Union


ConnectorScope = Union[
    Literal[
        "team",
        "personal",
    ],
    UnrecognizedStr,
]
r"""Scope determines visibility and access control for connectors:<br>
<ul>
<li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
<li><code>personal</code> - Private to the creating user only</li>
</ul>

"""
