"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ConnectorStatsTypedDict(TypedDict):
    r"""Statistics for a connector's records"""

    connector_id: NotRequired[str]
    total_records: NotRequired[int]
    indexed_records: NotRequired[int]
    failed_records: NotRequired[int]
    pending_records: NotRequired[int]
    last_sync_time: NotRequired[int]
    status_breakdown: NotRequired[Dict[str, int]]


class ConnectorStats(BaseModel):
    r"""Statistics for a connector's records"""

    connector_id: Annotated[Optional[str], pydantic.Field(alias="connectorId")] = None

    total_records: Annotated[Optional[int], pydantic.Field(alias="totalRecords")] = None

    indexed_records: Annotated[
        Optional[int], pydantic.Field(alias="indexedRecords")
    ] = None

    failed_records: Annotated[Optional[int], pydantic.Field(alias="failedRecords")] = (
        None
    )

    pending_records: Annotated[
        Optional[int], pydantic.Field(alias="pendingRecords")
    ] = None

    last_sync_time: Annotated[Optional[int], pydantic.Field(alias="lastSyncTime")] = (
        None
    )

    status_breakdown: Annotated[
        Optional[Dict[str, int]], pydantic.Field(alias="statusBreakdown")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connectorId",
                "totalRecords",
                "indexedRecords",
                "failedRecords",
                "pendingRecords",
                "lastSyncTime",
                "statusBreakdown",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ConnectorStats.model_rebuild()
except NameError:
    pass
