"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, SecurityMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CONNECTOR_REINDEX_FAILED_RECORDS_OP_SERVERS = [
    # Connector Service (Internal)
    "http://localhost:8088",
]


class ConnectorReindexFailedRecordsSecurityTypedDict(TypedDict):
    scoped_token: str


class ConnectorReindexFailedRecordsSecurity(BaseModel):
    scoped_token: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ]


class ConnectorReindexFailedRecordsRequestTypedDict(TypedDict):
    r"""Request payload"""

    connector: NotRequired[str]
    r"""Connector name to reindex failed records for"""


class ConnectorReindexFailedRecordsRequest(BaseModel):
    r"""Request payload"""

    connector: Optional[str] = None
    r"""Connector name to reindex failed records for"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connector"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConnectorReindexFailedRecordsResponseTypedDict(TypedDict):
    r"""Reindexing triggered"""

    success: NotRequired[bool]
    message: NotRequired[str]
    count: NotRequired[int]
    r"""Number of records queued for reindexing"""


class ConnectorReindexFailedRecordsResponse(BaseModel):
    r"""Reindexing triggered"""

    success: Optional[bool] = None

    message: Optional[str] = None

    count: Optional[int] = None
    r"""Number of records queued for reindexing"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
