"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthSchemaTypedDict(TypedDict):
    r"""JSON Schema for authentication fields"""


class AuthSchema(BaseModel):
    r"""JSON Schema for authentication fields"""


class SyncSchemaTypedDict(TypedDict):
    r"""JSON Schema for sync configuration"""


class SyncSchema(BaseModel):
    r"""JSON Schema for sync configuration"""


class FilterSchemaTypedDict(TypedDict):
    r"""JSON Schema for filter options"""


class FilterSchema(BaseModel):
    r"""JSON Schema for filter options"""


class ConnectorSchemaTypedDict(TypedDict):
    r"""Schema definition for configuring a connector type"""

    connector_type: NotRequired[str]
    auth_schema: NotRequired[AuthSchemaTypedDict]
    r"""JSON Schema for authentication fields"""
    sync_schema: NotRequired[SyncSchemaTypedDict]
    r"""JSON Schema for sync configuration"""
    filter_schema: NotRequired[FilterSchemaTypedDict]
    r"""JSON Schema for filter options"""
    required_fields: NotRequired[List[str]]
    r"""Required field names"""


class ConnectorSchema(BaseModel):
    r"""Schema definition for configuring a connector type"""

    connector_type: Annotated[Optional[str], pydantic.Field(alias="connectorType")] = (
        None
    )

    auth_schema: Annotated[Optional[AuthSchema], pydantic.Field(alias="authSchema")] = (
        None
    )
    r"""JSON Schema for authentication fields"""

    sync_schema: Annotated[Optional[SyncSchema], pydantic.Field(alias="syncSchema")] = (
        None
    )
    r"""JSON Schema for sync configuration"""

    filter_schema: Annotated[
        Optional[FilterSchema], pydantic.Field(alias="filterSchema")
    ] = None
    r"""JSON Schema for filter options"""

    required_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="requiredFields")
    ] = None
    r"""Required field names"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connectorType",
                "authSchema",
                "syncSchema",
                "filterSchema",
                "requiredFields",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ConnectorSchema.model_rebuild()
except NameError:
    pass
