"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CreateOAuthAppRequestAllowedGrantType = Literal[
    "authorization_code",
    "client_credentials",
    "refresh_token",
]


class CreateOAuthAppRequestTypedDict(TypedDict):
    r"""Request to create a new OAuth app"""

    name: str
    r"""App name (displayed to users during authorization)"""
    redirect_uris: List[str]
    r"""Allowed redirect URIs (1-10 URIs)"""
    allowed_scopes: List[str]
    r"""Scopes the app can request"""
    description: NotRequired[str]
    r"""App description"""
    allowed_grant_types: NotRequired[List[CreateOAuthAppRequestAllowedGrantType]]
    r"""Allowed grant types. Defaults to all if not specified.

    """
    homepage_url: NotRequired[str]
    r"""App homepage URL (shown during authorization)"""
    privacy_policy_url: NotRequired[str]
    r"""Privacy policy URL"""
    terms_of_service_url: NotRequired[str]
    r"""Terms of service URL"""
    is_confidential: NotRequired[bool]
    r"""Whether the app can securely store secrets.
    - `true`: Server-side app (secret required for token requests)
    - `false`: Browser/mobile app (must use PKCE)

    """
    access_token_lifetime: NotRequired[int]
    r"""Access token lifetime in seconds (300-86400)"""
    refresh_token_lifetime: NotRequired[int]
    r"""Refresh token lifetime in seconds (3600-31536000)"""


class CreateOAuthAppRequest(BaseModel):
    r"""Request to create a new OAuth app"""

    name: str
    r"""App name (displayed to users during authorization)"""

    redirect_uris: Annotated[List[str], pydantic.Field(alias="redirectUris")]
    r"""Allowed redirect URIs (1-10 URIs)"""

    allowed_scopes: Annotated[List[str], pydantic.Field(alias="allowedScopes")]
    r"""Scopes the app can request"""

    description: Optional[str] = None
    r"""App description"""

    allowed_grant_types: Annotated[
        Optional[List[CreateOAuthAppRequestAllowedGrantType]],
        pydantic.Field(alias="allowedGrantTypes"),
    ] = None
    r"""Allowed grant types. Defaults to all if not specified.

    """

    homepage_url: Annotated[Optional[str], pydantic.Field(alias="homepageUrl")] = None
    r"""App homepage URL (shown during authorization)"""

    privacy_policy_url: Annotated[
        Optional[str], pydantic.Field(alias="privacyPolicyUrl")
    ] = None
    r"""Privacy policy URL"""

    terms_of_service_url: Annotated[
        Optional[str], pydantic.Field(alias="termsOfServiceUrl")
    ] = None
    r"""Terms of service URL"""

    is_confidential: Annotated[
        Optional[bool], pydantic.Field(alias="isConfidential")
    ] = True
    r"""Whether the app can securely store secrets.
    - `true`: Server-side app (secret required for token requests)
    - `false`: Browser/mobile app (must use PKCE)

    """

    access_token_lifetime: Annotated[
        Optional[int], pydantic.Field(alias="accessTokenLifetime")
    ] = 3600
    r"""Access token lifetime in seconds (300-86400)"""

    refresh_token_lifetime: Annotated[
        Optional[int], pydantic.Field(alias="refreshTokenLifetime")
    ] = 604800
    r"""Refresh token lifetime in seconds (3600-31536000)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "allowedGrantTypes",
                "homepageUrl",
                "privacyPolicyUrl",
                "termsOfServiceUrl",
                "isConfidential",
                "accessTokenLifetime",
                "refreshTokenLifetime",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateOAuthAppRequest.model_rebuild()
except NameError:
    pass
