"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateAgentTemplateConfigSchemaTypedDict(TypedDict):
    r"""JSON Schema for customization"""


class CreateAgentTemplateConfigSchema(BaseModel):
    r"""JSON Schema for customization"""


class CreateAgentTemplateRequestTypedDict(TypedDict):
    r"""Request payload"""

    name: str
    r"""Template name"""
    description: NotRequired[str]
    r"""What agents from this template do"""
    category: NotRequired[str]
    r"""Template category"""
    default_system_prompt: NotRequired[str]
    r"""Default system instructions"""
    recommended_tools: NotRequired[List[str]]
    r"""Suggested tool keys"""
    config_schema: NotRequired[CreateAgentTemplateConfigSchemaTypedDict]
    r"""JSON Schema for customization"""
    is_public: NotRequired[bool]
    r"""Make template available organization-wide"""


class CreateAgentTemplateRequest(BaseModel):
    r"""Request payload"""

    name: str
    r"""Template name"""

    description: Optional[str] = None
    r"""What agents from this template do"""

    category: Optional[str] = None
    r"""Template category"""

    default_system_prompt: Annotated[
        Optional[str], pydantic.Field(alias="defaultSystemPrompt")
    ] = None
    r"""Default system instructions"""

    recommended_tools: Annotated[
        Optional[List[str]], pydantic.Field(alias="recommendedTools")
    ] = None
    r"""Suggested tool keys"""

    config_schema: Annotated[
        Optional[CreateAgentTemplateConfigSchema], pydantic.Field(alias="configSchema")
    ] = None
    r"""JSON Schema for customization"""

    is_public: Annotated[Optional[bool], pydantic.Field(alias="isPublic")] = False
    r"""Make template available organization-wide"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "category",
                "defaultSystemPrompt",
                "recommendedTools",
                "configSchema",
                "isPublic",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateAgentTemplateRequest.model_rebuild()
except NameError:
    pass
