"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel
import pydantic
from typing import Literal
from typing_extensions import Annotated, TypedDict


CreateS3StorageConfigStorageType = Literal["s3",]
r"""Storage type identifier"""


class CreateS3StorageConfigRequestTypedDict(TypedDict):
    r"""Request body for Configure AWS S3 Storage"""

    storage_type: CreateS3StorageConfigStorageType
    r"""Storage type identifier"""
    s3_access_key_id: str
    r"""AWS IAM access key ID with S3 permissions"""
    s3_secret_access_key: str
    r"""AWS IAM secret access key"""
    s3_region: str
    r"""AWS region where the S3 bucket is located"""
    s3_bucket_name: str
    r"""Name of the S3 bucket for storing files"""


class CreateS3StorageConfigRequest(BaseModel):
    r"""Request body for Configure AWS S3 Storage"""

    storage_type: Annotated[
        CreateS3StorageConfigStorageType, pydantic.Field(alias="storageType")
    ]
    r"""Storage type identifier"""

    s3_access_key_id: Annotated[str, pydantic.Field(alias="s3AccessKeyId")]
    r"""AWS IAM access key ID with S3 permissions"""

    s3_secret_access_key: Annotated[str, pydantic.Field(alias="s3SecretAccessKey")]
    r"""AWS IAM secret access key"""

    s3_region: Annotated[str, pydantic.Field(alias="s3Region")]
    r"""AWS region where the S3 bucket is located"""

    s3_bucket_name: Annotated[str, pydantic.Field(alias="s3BucketName")]
    r"""Name of the S3 bucket for storing files"""


try:
    CreateS3StorageConfigRequest.model_rebuild()
except NameError:
    pass
