"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jobstatus import JobStatus, JobStatusTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetAllCrawlingJobStatusResponseTypedDict(TypedDict):
    r"""All job statuses retrieved successfully"""

    success: NotRequired[bool]
    message: NotRequired[str]
    data: NotRequired[List[JobStatusTypedDict]]


class GetAllCrawlingJobStatusResponse(BaseModel):
    r"""All job statuses retrieved successfully"""

    success: Optional[bool] = None

    message: Optional[str] = None

    data: Optional[List[JobStatus]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
