"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectorinstance import ConnectorInstance, ConnectorInstanceTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetConnectorInstanceRequestTypedDict(TypedDict):
    connector_id: str
    r"""Connector instance ID"""


class GetConnectorInstanceRequest(BaseModel):
    connector_id: Annotated[
        str,
        pydantic.Field(alias="connectorId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Connector instance ID"""


class GetConnectorInstanceResponseTypedDict(TypedDict):
    r"""Instance retrieved"""

    success: NotRequired[bool]
    connector: NotRequired[ConnectorInstanceTypedDict]
    r"""A configured connector instance. Represents an active or configured
    connection to an external service.

    """


class GetConnectorInstanceResponse(BaseModel):
    r"""Instance retrieved"""

    success: Optional[bool] = None

    connector: Optional[ConnectorInstance] = None
    r"""A configured connector instance. Represents an active or configured
    connection to an external service.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "connector"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
