"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetDocumentBufferRequestTypedDict(TypedDict):
    document_id: str
    r"""Document ID (24-character MongoDB ObjectId)"""
    version: NotRequired[int]
    r"""Version number to retrieve (0-indexed)"""


class GetDocumentBufferRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Document ID (24-character MongoDB ObjectId)"""

    version: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Version number to retrieve (0-indexed)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
