"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StepTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    is_completed: NotRequired[bool]
    is_required: NotRequired[bool]


class Step(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    is_completed: Annotated[Optional[bool], pydantic.Field(alias="isCompleted")] = None

    is_required: Annotated[Optional[bool], pydantic.Field(alias="isRequired")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "isCompleted", "isRequired"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetOnboardingStatusDataTypedDict(TypedDict):
    is_completed: NotRequired[bool]
    r"""Whether onboarding is fully complete"""
    current_step: NotRequired[str]
    r"""Current active onboarding step"""
    completed_steps: NotRequired[List[str]]
    completion_percentage: NotRequired[int]
    steps: NotRequired[List[StepTypedDict]]


class GetOnboardingStatusData(BaseModel):
    is_completed: Annotated[Optional[bool], pydantic.Field(alias="isCompleted")] = None
    r"""Whether onboarding is fully complete"""

    current_step: Annotated[Optional[str], pydantic.Field(alias="currentStep")] = None
    r"""Current active onboarding step"""

    completed_steps: Annotated[
        Optional[List[str]], pydantic.Field(alias="completedSteps")
    ] = None

    completion_percentage: Annotated[
        Optional[int], pydantic.Field(alias="completionPercentage")
    ] = None

    steps: Optional[List[Step]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "isCompleted",
                "currentStep",
                "completedSteps",
                "completionPercentage",
                "steps",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetOnboardingStatusResponseTypedDict(TypedDict):
    r"""Onboarding status retrieved successfully"""

    success: NotRequired[bool]
    data: NotRequired[GetOnboardingStatusDataTypedDict]


class GetOnboardingStatusResponse(BaseModel):
    r"""Onboarding status retrieved successfully"""

    success: Optional[bool] = None

    data: Optional[GetOnboardingStatusData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Step.model_rebuild()
except NameError:
    pass
try:
    GetOnboardingStatusData.model_rebuild()
except NameError:
    pass
