"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetUsersByIdsRequestTypedDict(TypedDict):
    r"""Request payload"""

    user_ids: List[str]
    r"""Array of user IDs to retrieve"""


class GetUsersByIdsRequest(BaseModel):
    r"""Request payload"""

    user_ids: Annotated[List[str], pydantic.Field(alias="userIds")]
    r"""Array of user IDs to retrieve"""


class GetUsersByIdsResponseTypedDict(TypedDict):
    r"""Users retrieved successfully"""

    success: NotRequired[bool]
    data: NotRequired[List[UserTypedDict]]
    requested_count: NotRequired[int]
    r"""Number of IDs requested"""
    found_count: NotRequired[int]
    r"""Number of users found"""


class GetUsersByIdsResponse(BaseModel):
    r"""Users retrieved successfully"""

    success: Optional[bool] = None

    data: Optional[List[User]] = None

    requested_count: Annotated[
        Optional[int], pydantic.Field(alias="requestedCount")
    ] = None
    r"""Number of IDs requested"""

    found_count: Annotated[Optional[int], pydantic.Field(alias="foundCount")] = None
    r"""Number of users found"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "requestedCount", "foundCount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetUsersByIdsRequest.model_rebuild()
except NameError:
    pass
try:
    GetUsersByIdsResponse.model_rebuild()
except NameError:
    pass
