"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetUsersInGroupRequestTypedDict(TypedDict):
    group_id: str
    r"""Unique identifier of the user group"""
    page: NotRequired[int]
    r"""Page number for pagination (1-based)"""
    limit: NotRequired[int]
    r"""Number of users per page"""


class GetUsersInGroupRequest(BaseModel):
    group_id: Annotated[
        str,
        pydantic.Field(alias="groupId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the user group"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number for pagination (1-based)"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20
    r"""Number of users per page"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetUsersInGroupPaginationTypedDict(TypedDict):
    page: NotRequired[int]
    limit: NotRequired[int]
    total: NotRequired[int]
    total_pages: NotRequired[int]


class GetUsersInGroupPagination(BaseModel):
    page: Optional[int] = None

    limit: Optional[int] = None

    total: Optional[int] = None

    total_pages: Annotated[Optional[int], pydantic.Field(alias="totalPages")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "limit", "total", "totalPages"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetUsersInGroupResponseTypedDict(TypedDict):
    r"""Users in group retrieved successfully"""

    success: NotRequired[bool]
    data: NotRequired[List[UserTypedDict]]
    pagination: NotRequired[GetUsersInGroupPaginationTypedDict]


class GetUsersInGroupResponse(BaseModel):
    r"""Users in group retrieved successfully"""

    success: Optional[bool] = None

    data: Optional[List[User]] = None

    pagination: Optional[GetUsersInGroupPagination] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetUsersInGroupPagination.model_rebuild()
except NameError:
    pass
