"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from typing import Union
from typing_extensions import TypeAliasType


GetUserDisplayPictureResponseTypedDict = TypeAliasType(
    "GetUserDisplayPictureResponseTypedDict", Union[httpx.Response, httpx.Response]
)


GetUserDisplayPictureResponse = TypeAliasType(
    "GetUserDisplayPictureResponse", Union[httpx.Response, httpx.Response]
)
