"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations


GMAIL_WEBHOOK_VERIFY_OP_SERVERS = [
    # Connector Service (Internal)
    "http://localhost:8088",
]
