"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HandleOAuthCallbackRequestTypedDict(TypedDict):
    code: NotRequired[str]
    r"""Authorization code from provider"""
    state: NotRequired[str]
    r"""State parameter (contains connector ID)"""
    error: NotRequired[str]
    r"""Error code if authorization failed"""
    base_url: NotRequired[str]
    r"""Base URL for redirect"""


class HandleOAuthCallbackRequest(BaseModel):
    code: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Authorization code from provider"""

    state: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""State parameter (contains connector ID)"""

    error: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Error code if authorization failed"""

    base_url: Annotated[
        Optional[str],
        pydantic.Field(alias="baseUrl"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Base URL for redirect"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "state", "error", "baseUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HandleOAuthCallbackResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class HandleOAuthCallbackResponse(BaseModel):
    headers: Dict[str, List[str]]
