"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .initauthresponse import InitAuthResponse, InitAuthResponseTypedDict
from pipeshub.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class InitAuthResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: InitAuthResponseTypedDict


class InitAuthResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: InitAuthResponse
