"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel
from typing_extensions import TypedDict


class InitAuthRequestTypedDict(TypedDict):
    r"""Request to initialize authentication session"""

    email: str
    r"""User email address (RFC 5321 compliant)"""


class InitAuthRequest(BaseModel):
    r"""Request to initialize authentication session"""

    email: str
    r"""User email address (RFC 5321 compliant)"""
