"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


KnowledgeHubNodeType = Union[
    Literal[
        "KB",
        "FOLDER",
        "RECORD",
        "CONNECTOR",
        "APP",
    ],
    UnrecognizedStr,
]


class KnowledgeHubNodeMetadataTypedDict(TypedDict):
    pass


class KnowledgeHubNodeMetadata(BaseModel):
    pass


class KnowledgeHubNodeTypedDict(TypedDict):
    r"""A node in the knowledge hub tree structure"""

    id: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[KnowledgeHubNodeType]
    parent_id: NotRequired[str]
    has_children: NotRequired[bool]
    child_count: NotRequired[int]
    metadata: NotRequired[KnowledgeHubNodeMetadataTypedDict]


class KnowledgeHubNode(BaseModel):
    r"""A node in the knowledge hub tree structure"""

    id: Optional[str] = None

    name: Optional[str] = None

    type: Optional[KnowledgeHubNodeType] = None

    parent_id: Annotated[Optional[str], pydantic.Field(alias="parentId")] = None

    has_children: Annotated[Optional[bool], pydantic.Field(alias="hasChildren")] = None

    child_count: Annotated[Optional[int], pydantic.Field(alias="childCount")] = None

    metadata: Optional[KnowledgeHubNodeMetadata] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "name", "type", "parentId", "hasChildren", "childCount", "metadata"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    KnowledgeHubNode.model_rebuild()
except NameError:
    pass
