"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MonthlyScheduleConfigTypedDict(TypedDict):
    r"""Run crawling job on a specified day of each month"""

    day_of_month: int
    r"""Day of the month to run (1-31). If day doesn't exist in month, job runs on last day."""
    hour: int
    r"""Hour of the day to run (0-23)"""
    minute: int
    r"""Minute of the hour to run (0-59)"""
    schedule_type: Literal["monthly"]
    is_enabled: NotRequired[bool]
    r"""Whether the schedule is active. Disabled schedules won't create new jobs."""
    timezone: NotRequired[str]
    r"""IANA timezone identifier (e.g., \"America/New_York\", \"Europe/London\", \"Asia/Tokyo\")"""


class MonthlyScheduleConfig(BaseModel):
    r"""Run crawling job on a specified day of each month"""

    day_of_month: Annotated[int, pydantic.Field(alias="dayOfMonth")]
    r"""Day of the month to run (1-31). If day doesn't exist in month, job runs on last day."""

    hour: int
    r"""Hour of the day to run (0-23)"""

    minute: int
    r"""Minute of the hour to run (0-59)"""

    schedule_type: Annotated[
        Annotated[Literal["monthly"], AfterValidator(validate_const("monthly"))],
        pydantic.Field(alias="scheduleType"),
    ] = "monthly"

    is_enabled: Annotated[Optional[bool], pydantic.Field(alias="isEnabled")] = True
    r"""Whether the schedule is active. Disabled schedules won't create new jobs."""

    timezone: Optional[str] = "UTC"
    r"""IANA timezone identifier (e.g., \"America/New_York\", \"Europe/London\", \"Asia/Tokyo\")"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["isEnabled", "timezone"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    MonthlyScheduleConfig.model_rebuild()
except NameError:
    pass
