"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OAuthIntrospectResponseTypedDict(TypedDict):
    r"""OAuth 2.0 Token Introspection Response (RFC 7662).
    Contains token metadata if active, or just `active: false` if not.

    """

    active: bool
    r"""Whether the token is currently active"""
    scope: NotRequired[str]
    r"""Scopes granted to the token"""
    client_id: NotRequired[str]
    r"""Client ID the token was issued to"""
    username: NotRequired[str]
    r"""User identifier (if user-based token)"""
    token_type: NotRequired[str]
    r"""Token type"""
    exp: NotRequired[int]
    r"""Token expiration timestamp (Unix epoch)"""
    iat: NotRequired[int]
    r"""Token issuance timestamp (Unix epoch)"""
    nbf: NotRequired[int]
    r"""Token not-before timestamp (Unix epoch)"""
    sub: NotRequired[str]
    r"""Subject (user ID)"""
    aud: NotRequired[str]
    r"""Audience (client ID)"""
    iss: NotRequired[str]
    r"""Issuer URL"""
    jti: NotRequired[str]
    r"""Unique token identifier"""


class OAuthIntrospectResponse(BaseModel):
    r"""OAuth 2.0 Token Introspection Response (RFC 7662).
    Contains token metadata if active, or just `active: false` if not.

    """

    active: bool
    r"""Whether the token is currently active"""

    scope: Optional[str] = None
    r"""Scopes granted to the token"""

    client_id: Optional[str] = None
    r"""Client ID the token was issued to"""

    username: Optional[str] = None
    r"""User identifier (if user-based token)"""

    token_type: Optional[str] = None
    r"""Token type"""

    exp: Optional[int] = None
    r"""Token expiration timestamp (Unix epoch)"""

    iat: Optional[int] = None
    r"""Token issuance timestamp (Unix epoch)"""

    nbf: Optional[int] = None
    r"""Token not-before timestamp (Unix epoch)"""

    sub: Optional[str] = None
    r"""Subject (user ID)"""

    aud: Optional[str] = None
    r"""Audience (client ID)"""

    iss: Optional[str] = None
    r"""Issuer URL"""

    jti: Optional[str] = None
    r"""Unique token identifier"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "scope",
                "client_id",
                "username",
                "token_type",
                "exp",
                "iat",
                "nbf",
                "sub",
                "aud",
                "iss",
                "jti",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
