"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PasswordResetRequestTypedDict(TypedDict):
    r"""Request to reset password for authenticated user"""

    current_password: str
    r"""Current password for verification"""
    new_password: str
    r"""New password. Must meet the following requirements:
    - Minimum 8 characters
    - At least 1 uppercase letter
    - At least 1 lowercase letter
    - At least 1 number
    - At least 1 special character (#?!@$%^&*-)

    """
    cf_turnstile_response: NotRequired[str]
    r"""Cloudflare Turnstile CAPTCHA token (optional)"""


class PasswordResetRequest(BaseModel):
    r"""Request to reset password for authenticated user"""

    current_password: Annotated[str, pydantic.Field(alias="currentPassword")]
    r"""Current password for verification"""

    new_password: Annotated[str, pydantic.Field(alias="newPassword")]
    r"""New password. Must meet the following requirements:
    - Minimum 8 characters
    - At least 1 uppercase letter
    - At least 1 lowercase letter
    - At least 1 number
    - At least 1 special character (#?!@$%^&*-)

    """

    cf_turnstile_response: Annotated[
        Optional[str], pydantic.Field(alias="cf-turnstile-response")
    ] = None
    r"""Cloudflare Turnstile CAPTCHA token (optional)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cf-turnstile-response"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PasswordResetRequest.model_rebuild()
except NameError:
    pass
