"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel
from typing_extensions import TypedDict


class PasswordCredentialsTypedDict(TypedDict):
    r"""Credentials for password authentication"""

    password: str
    r"""User password"""


class PasswordCredentials(BaseModel):
    r"""Credentials for password authentication"""

    password: str
    r"""User password"""
