"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userbasic import UserBasic, UserBasicTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RefreshTokenResponseTypedDict(TypedDict):
    r"""Response with new access token"""

    user: NotRequired[UserBasicTypedDict]
    r"""Basic user information"""
    access_token: NotRequired[str]
    r"""New JWT access token (1 hour expiry)"""


class RefreshTokenResponse(BaseModel):
    r"""Response with new access token"""

    user: Optional[UserBasic] = None
    r"""Basic user information"""

    access_token: Annotated[Optional[str], pydantic.Field(alias="accessToken")] = None
    r"""New JWT access token (1 hour expiry)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["user", "accessToken"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    RefreshTokenResponse.model_rebuild()
except NameError:
    pass
