"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filters import Filters, FiltersTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RegenerateAgentAnswerRequestBodyTypedDict(TypedDict):
    r"""Request payload"""

    filters: NotRequired[FiltersTypedDict]
    model_key: NotRequired[str]
    chat_mode: NotRequired[str]


class RegenerateAgentAnswerRequestBody(BaseModel):
    r"""Request payload"""

    filters: Optional[Filters] = None

    model_key: Annotated[Optional[str], pydantic.Field(alias="modelKey")] = None

    chat_mode: Annotated[Optional[str], pydantic.Field(alias="chatMode")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filters", "modelKey", "chatMode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RegenerateAgentAnswerRequestTypedDict(TypedDict):
    agent_key: str
    conversation_id: str
    message_id: str
    body: NotRequired[RegenerateAgentAnswerRequestBodyTypedDict]
    r"""Request payload"""


class RegenerateAgentAnswerRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        Optional[RegenerateAgentAnswerRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Request payload"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    RegenerateAgentAnswerRequestBody.model_rebuild()
except NameError:
    pass
