"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict


class SaveConnectorFiltersRequestTypedDict(TypedDict):
    r"""Request to save filter selections for a connector"""

    filters: Dict[str, Any]
    r"""Filter values to save (structure depends on connector's filter schema)"""


class SaveConnectorFiltersRequest(BaseModel):
    r"""Request to save filter selections for a connector"""

    filters: Dict[str, Any]
    r"""Filter values to save (structure depends on connector's filter schema)"""
