"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sharerequest import ShareRequest, ShareRequestTypedDict
from pipeshub.types import BaseModel
from pipeshub.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class ShareSearchRequestTypedDict(TypedDict):
    search_id: str
    body: ShareRequestTypedDict
    r"""Request payload"""


class ShareSearchRequest(BaseModel):
    search_id: Annotated[
        str,
        pydantic.Field(alias="searchId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        ShareRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""
