"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SMTPConfigTypedDict(TypedDict):
    r"""SMTP email server configuration for sending system emails (invitations, notifications, password resets)"""

    host: str
    r"""SMTP server hostname or IP address"""
    port: int
    r"""SMTP server port. Common ports are 25 (unencrypted), 465 (SSL), 587 (TLS/STARTTLS)"""
    from_email: str
    r"""Default sender email address that appears in the \"From\" field of outgoing emails"""
    username: NotRequired[str]
    r"""SMTP authentication username. Usually an email address for services like Gmail, SendGrid, etc."""
    password: NotRequired[str]
    r"""SMTP authentication password or app-specific password. For Gmail, use an App Password instead of your account password."""


class SMTPConfig(BaseModel):
    r"""SMTP email server configuration for sending system emails (invitations, notifications, password resets)"""

    host: str
    r"""SMTP server hostname or IP address"""

    port: int
    r"""SMTP server port. Common ports are 25 (unencrypted), 465 (SSL), 587 (TLS/STARTTLS)"""

    from_email: Annotated[str, pydantic.Field(alias="fromEmail")]
    r"""Default sender email address that appears in the \"From\" field of outgoing emails"""

    username: Optional[str] = None
    r"""SMTP authentication username. Usually an email address for services like Gmail, SendGrid, etc."""

    password: Optional[str] = None
    r"""SMTP authentication password or app-specific password. For Gmail, use an App Password instead of your account password."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["username", "password"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SMTPConfig.model_rebuild()
except NameError:
    pass
