"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel
from pipeshub.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class UnshareAgentRequestBodyTypedDict(TypedDict):
    r"""Request body for Revoke agent access"""

    user_ids: List[str]


class UnshareAgentRequestBody(BaseModel):
    r"""Request body for Revoke agent access"""

    user_ids: Annotated[List[str], pydantic.Field(alias="userIds")]


class UnshareAgentRequestTypedDict(TypedDict):
    agent_key: str
    body: UnshareAgentRequestBodyTypedDict
    r"""Request body for Revoke agent access"""


class UnshareAgentRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        UnshareAgentRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request body for Revoke agent access"""


try:
    UnshareAgentRequestBody.model_rebuild()
except NameError:
    pass
