"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateAIModelProviderRequestConfigurationTypedDict(TypedDict):
    r"""Updated provider configuration"""


class UpdateAIModelProviderRequestConfiguration(BaseModel):
    r"""Updated provider configuration"""


class UpdateAIModelProviderRequestTypedDict(TypedDict):
    r"""Request to update an existing AI model provider"""

    provider: str
    r"""Provider name"""
    configuration: UpdateAIModelProviderRequestConfigurationTypedDict
    r"""Updated provider configuration"""
    is_multimodal: NotRequired[bool]
    is_reasoning: NotRequired[bool]
    is_default: NotRequired[bool]
    context_length: NotRequired[Nullable[int]]


class UpdateAIModelProviderRequest(BaseModel):
    r"""Request to update an existing AI model provider"""

    provider: str
    r"""Provider name"""

    configuration: UpdateAIModelProviderRequestConfiguration
    r"""Updated provider configuration"""

    is_multimodal: Annotated[Optional[bool], pydantic.Field(alias="isMultimodal")] = (
        None
    )

    is_reasoning: Annotated[Optional[bool], pydantic.Field(alias="isReasoning")] = None

    is_default: Annotated[Optional[bool], pydantic.Field(alias="isDefault")] = None

    context_length: Annotated[
        OptionalNullable[int], pydantic.Field(alias="contextLength")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["isMultimodal", "isReasoning", "isDefault", "contextLength"]
        )
        nullable_fields = set(["contextLength"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UpdateAIModelProviderRequest.model_rebuild()
except NameError:
    pass
