"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class UpdateConnectorNameRequestTypedDict(TypedDict):
    r"""Request to update connector instance name"""

    instance_name: str
    r"""New display name for the connector instance"""


class UpdateConnectorNameRequest(BaseModel):
    r"""Request to update connector instance name"""

    instance_name: Annotated[str, pydantic.Field(alias="instanceName")]
    r"""New display name for the connector instance"""


try:
    UpdateConnectorNameRequest.model_rebuild()
except NameError:
    pass
