"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectorfiltersconfig import (
    ConnectorFiltersConfig,
    ConnectorFiltersConfigTypedDict,
)
from .connectorsyncconfig import ConnectorSyncConfig, ConnectorSyncConfigTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateConnectorFiltersSyncRequestTypedDict(TypedDict):
    r"""Request to update filters and sync config (connector must be authenticated and inactive)"""

    sync: NotRequired[ConnectorSyncConfigTypedDict]
    r"""Synchronization configuration for a connector instance"""
    filters: NotRequired[ConnectorFiltersConfigTypedDict]
    r"""Filter configuration to control what data is synced (sync filters and indexing filters)"""
    base_url: NotRequired[str]


class UpdateConnectorFiltersSyncRequest(BaseModel):
    r"""Request to update filters and sync config (connector must be authenticated and inactive)"""

    sync: Optional[ConnectorSyncConfig] = None
    r"""Synchronization configuration for a connector instance"""

    filters: Optional[ConnectorFiltersConfig] = None
    r"""Filter configuration to control what data is synced (sync filters and indexing filters)"""

    base_url: Annotated[Optional[str], pydantic.Field(alias="baseUrl")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sync", "filters", "baseUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    UpdateConnectorFiltersSyncRequest.model_rebuild()
except NameError:
    pass
