"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateKnowledgeBaseRequestBodyTypedDict(TypedDict):
    r"""Request payload"""

    kb_name: NotRequired[str]
    r"""New name for the knowledge base"""


class UpdateKnowledgeBaseRequestBody(BaseModel):
    r"""Request payload"""

    kb_name: Annotated[Optional[str], pydantic.Field(alias="kbName")] = None
    r"""New name for the knowledge base"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["kbName"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateKnowledgeBaseRequestTypedDict(TypedDict):
    kb_id: str
    r"""Knowledge base ID"""
    body: UpdateKnowledgeBaseRequestBodyTypedDict
    r"""Request payload"""


class UpdateKnowledgeBaseRequest(BaseModel):
    kb_id: Annotated[
        str,
        pydantic.Field(alias="kbId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Knowledge base ID"""

    body: Annotated[
        UpdateKnowledgeBaseRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""


try:
    UpdateKnowledgeBaseRequestBody.model_rebuild()
except NameError:
    pass
