"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .modeltype import ModelType
from .updateaimodelproviderrequest import (
    UpdateAIModelProviderRequest,
    UpdateAIModelProviderRequestTypedDict,
)
from pipeshub.types import BaseModel
from pipeshub.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class UpdateAIModelProviderRequestRequestTypedDict(TypedDict):
    model_type: ModelType
    r"""Type of AI model"""
    model_key: str
    r"""Unique model key (UUID)"""
    body: UpdateAIModelProviderRequestTypedDict
    r"""Request payload"""


class UpdateAIModelProviderRequestRequest(BaseModel):
    model_type: Annotated[
        ModelType,
        pydantic.Field(alias="modelType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Type of AI model"""

    model_key: Annotated[
        str,
        pydantic.Field(alias="modelKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique model key (UUID)"""

    body: Annotated[
        UpdateAIModelProviderRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""
