"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .smtpconfig import SMTPConfig, SMTPConfigTypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, SecurityMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateSMTPConfigSecurityTypedDict(TypedDict):
    scoped_token: str


class UpdateSMTPConfigSecurity(BaseModel):
    scoped_token: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ]


class UpdateSMTPConfigResponseTypedDict(TypedDict):
    r"""SMTP configuration reloaded successfully"""

    message: NotRequired[str]
    r"""Success message"""
    smtp: NotRequired[SMTPConfigTypedDict]
    r"""SMTP email server configuration for sending system emails (invitations, notifications, password resets)"""


class UpdateSMTPConfigResponse(BaseModel):
    r"""SMTP configuration reloaded successfully"""

    message: Optional[str] = None
    r"""Success message"""

    smtp: Optional[SMTPConfig] = None
    r"""SMTP email server configuration for sending system emails (invitations, notifications, password resets)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message", "smtp"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
