"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import io
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import (
    FieldMetadata,
    MultipartFormMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import IO, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UploadRecordsToKBFileTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class UploadRecordsToKBFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UploadRecordsToKBRequestBodyTypedDict(TypedDict):
    r"""Request payload"""

    files: List[UploadRecordsToKBFileTypedDict]
    r"""Files to upload (max 1000)"""
    files_metadata: NotRequired[str]
    r"""JSON array with file_path and last_modified for each file"""
    is_versioned: NotRequired[bool]
    r"""Enable version tracking"""
    record_type: NotRequired[str]
    r"""Type of records to create"""


class UploadRecordsToKBRequestBody(BaseModel):
    r"""Request payload"""

    files: Annotated[
        List[UploadRecordsToKBFile],
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ]
    r"""Files to upload (max 1000)"""

    files_metadata: Annotated[Optional[str], FieldMetadata(multipart=True)] = None
    r"""JSON array with file_path and last_modified for each file"""

    is_versioned: Annotated[
        Optional[bool],
        pydantic.Field(alias="isVersioned"),
        FieldMetadata(multipart=True),
    ] = True
    r"""Enable version tracking"""

    record_type: Annotated[
        Optional[str], pydantic.Field(alias="recordType"), FieldMetadata(multipart=True)
    ] = "FILE"
    r"""Type of records to create"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["files_metadata", "isVersioned", "recordType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UploadRecordsToKBRequestTypedDict(TypedDict):
    kb_id: str
    r"""Knowledge base ID"""
    body: UploadRecordsToKBRequestBodyTypedDict
    r"""Request payload"""


class UploadRecordsToKBRequest(BaseModel):
    kb_id: Annotated[
        str,
        pydantic.Field(alias="kbId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Knowledge base ID"""

    body: Annotated[
        UploadRecordsToKBRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]
    r"""Request payload"""
