workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Pipeshub API:
        inputs:
            - location: registry.speakeasyapi.dev/pipeshub/test/pipes-hub-api
        output: .speakeasy/pipeshub-open-api.yaml
targets:
    pipeshub:
        target: python
        source: Pipeshub API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/pipeshub/test/pipeshub-oas-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
