workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PipesHub API:
        inputs:
            - location: /Users/anshika/work/PipesHub/pipeshub-sdk-python/pipeshub-openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/pipeshub/test/pipes-hub-api
targets:
    pipeshub:
        target: python
        source: PipesHub API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/pipeshub/test/pipes-hub-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
