"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "pipeshub"
__version__: str = "0.0.3"
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.824.1"
__user_agent__: str = "speakeasy-sdk/python 0.0.3 2.824.1 1.0.0 pipeshub"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
