"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from pipeshub import errors, models, utils
from pipeshub._hooks import HookContext
from pipeshub.types import OptionalNullable, UNSET
from pipeshub.utils import get_security_from_env
from pipeshub.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional


class ConnectorRegistry(BaseSDK):
    def list(
        self,
        *,
        scope: Optional[models.ConnectorScope] = None,
        page: Optional[int] = 1,
        limit: Optional[int] = 20,
        search: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetConnectorRegistryResponse:
        r"""List available connector types

        Get all available connector types from the registry.<br><br>
        <b>Overview:</b><br>
        The registry contains all connector types that can be configured as instances.
        Each type has specific authentication requirements, supported scopes, and capabilities.<br><br>
        <b>Connector Types Include:</b><br>
        <ul>
        <li><b>Google Workspace:</b> Drive, Gmail, Calendar, etc.</li>
        <li><b>Microsoft 365:</b> OneDrive, Outlook, SharePoint, etc.</li>
        <li><b>Cloud Storage:</b> Dropbox, Box, AWS S3</li>
        <li><b>Collaboration:</b> Slack, Confluence, Notion, Jira</li>
        <li><b>Databases:</b> PostgreSQL, MySQL, MongoDB</li>
        </ul>
        <b>Filtering:</b><br>
        Use <code>scope</code> to filter by team or personal connectors.
        Use <code>search</code> for full-text search across connector names.


        :param scope: Filter by scope type
        :param page: Page number
        :param limit: Items per page
        :param search: Search term for connector names
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetConnectorRegistryRequest(
            scope=scope,
            page=page,
            limit=limit,
            search=search,
        )

        req = self._build_request(
            method="GET",
            path="/connectors/registry",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getConnectorRegistry",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.GetConnectorRegistryResponse, http_res
            )
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        scope: Optional[models.ConnectorScope] = None,
        page: Optional[int] = 1,
        limit: Optional[int] = 20,
        search: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetConnectorRegistryResponse:
        r"""List available connector types

        Get all available connector types from the registry.<br><br>
        <b>Overview:</b><br>
        The registry contains all connector types that can be configured as instances.
        Each type has specific authentication requirements, supported scopes, and capabilities.<br><br>
        <b>Connector Types Include:</b><br>
        <ul>
        <li><b>Google Workspace:</b> Drive, Gmail, Calendar, etc.</li>
        <li><b>Microsoft 365:</b> OneDrive, Outlook, SharePoint, etc.</li>
        <li><b>Cloud Storage:</b> Dropbox, Box, AWS S3</li>
        <li><b>Collaboration:</b> Slack, Confluence, Notion, Jira</li>
        <li><b>Databases:</b> PostgreSQL, MySQL, MongoDB</li>
        </ul>
        <b>Filtering:</b><br>
        Use <code>scope</code> to filter by team or personal connectors.
        Use <code>search</code> for full-text search across connector names.


        :param scope: Filter by scope type
        :param page: Page number
        :param limit: Items per page
        :param search: Search term for connector names
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetConnectorRegistryRequest(
            scope=scope,
            page=page,
            limit=limit,
            search=search,
        )

        req = self._build_request_async(
            method="GET",
            path="/connectors/registry",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getConnectorRegistry",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.GetConnectorRegistryResponse, http_res
            )
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def get_schema(
        self,
        *,
        connector_type: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetConnectorSchemaResponse:
        r"""Get connector configuration schema

        Get the configuration schema for a specific connector type.<br><br>
        <b>Overview:</b><br>
        Returns JSON Schema definitions for authentication, sync settings, and
        filter options. Use this to dynamically build configuration forms.<br><br>
        <b>Schema Sections:</b><br>
        <ul>
        <li><b>authSchema:</b> Fields for authentication (credentials, tokens)</li>
        <li><b>syncSchema:</b> Sync settings (schedule, incremental options)</li>
        <li><b>filterSchema:</b> Filter field definitions</li>
        </ul>


        :param connector_type: Connector type identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetConnectorSchemaRequest(
            connector_type=connector_type,
        )

        req = self._build_request(
            method="GET",
            path="/connectors/registry/{connectorType}/schema",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getConnectorSchema",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GetConnectorSchemaResponse, http_res)
        if utils.match_response(http_res, ["401", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def get_schema_async(
        self,
        *,
        connector_type: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetConnectorSchemaResponse:
        r"""Get connector configuration schema

        Get the configuration schema for a specific connector type.<br><br>
        <b>Overview:</b><br>
        Returns JSON Schema definitions for authentication, sync settings, and
        filter options. Use this to dynamically build configuration forms.<br><br>
        <b>Schema Sections:</b><br>
        <ul>
        <li><b>authSchema:</b> Fields for authentication (credentials, tokens)</li>
        <li><b>syncSchema:</b> Sync settings (schedule, incremental options)</li>
        <li><b>filterSchema:</b> Filter field definitions</li>
        </ul>


        :param connector_type: Connector type identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetConnectorSchemaRequest(
            connector_type=connector_type,
        )

        req = self._build_request_async(
            method="GET",
            path="/connectors/registry/{connectorType}/schema",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getConnectorSchema",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GetConnectorSchemaResponse, http_res)
        if utils.match_response(http_res, ["401", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
