"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from pipeshub import errors, models, utils
from pipeshub._hooks import HookContext
from pipeshub.types import OptionalNullable, UNSET
from pipeshub.utils import get_security_from_env
from pipeshub.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional, Union


class ConnectorConfiguration(BaseSDK):
    def update_config(
        self,
        *,
        connector_id: str,
        auth: Optional[
            Union[models.ConnectorAuthConfig, models.ConnectorAuthConfigTypedDict]
        ] = None,
        sync: Optional[
            Union[models.ConnectorSyncConfig, models.ConnectorSyncConfigTypedDict]
        ] = None,
        filters: Optional[
            Union[models.ConnectorFiltersConfig, models.ConnectorFiltersConfigTypedDict]
        ] = None,
        base_url: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateConnectorConfigResponse:
        r"""Update connector configuration

        Update authentication, sync, and filter configuration.<br><br>
        <b>Prerequisites:</b><br>
        Connector must be <b>disabled</b> before updating configuration.
        Disable it first using <code>POST /{id}/toggle</code>.<br><br>
        <b>Partial Updates:</b><br>
        Only provide the sections you want to update. Omitted sections
        are not modified.


        :param connector_id:
        :param auth: Authentication configuration for a connector instance
        :param sync: Synchronization configuration for a connector instance
        :param filters: Filter configuration to control what data is synced (sync filters and indexing filters)
        :param base_url: Base URL for self-hosted instances
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url_ = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url_ = server_url
        else:
            base_url_ = self._get_url(base_url_, url_variables)

        request = models.UpdateConnectorConfigRequestRequest(
            connector_id=connector_id,
            body=models.UpdateConnectorConfigRequest(
                auth=utils.get_pydantic_model(
                    auth, Optional[models.ConnectorAuthConfig]
                ),
                sync=utils.get_pydantic_model(
                    sync, Optional[models.ConnectorSyncConfig]
                ),
                filters=utils.get_pydantic_model(
                    filters, Optional[models.ConnectorFiltersConfig]
                ),
                base_url=base_url,
            ),
        )

        req = self._build_request(
            method="PUT",
            path="/connectors/{connectorId}/config",
            base_url=base_url_,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.UpdateConnectorConfigRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url_ or "",
                operation_id="updateConnectorConfig",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.UpdateConnectorConfigResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def update_config_async(
        self,
        *,
        connector_id: str,
        auth: Optional[
            Union[models.ConnectorAuthConfig, models.ConnectorAuthConfigTypedDict]
        ] = None,
        sync: Optional[
            Union[models.ConnectorSyncConfig, models.ConnectorSyncConfigTypedDict]
        ] = None,
        filters: Optional[
            Union[models.ConnectorFiltersConfig, models.ConnectorFiltersConfigTypedDict]
        ] = None,
        base_url: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateConnectorConfigResponse:
        r"""Update connector configuration

        Update authentication, sync, and filter configuration.<br><br>
        <b>Prerequisites:</b><br>
        Connector must be <b>disabled</b> before updating configuration.
        Disable it first using <code>POST /{id}/toggle</code>.<br><br>
        <b>Partial Updates:</b><br>
        Only provide the sections you want to update. Omitted sections
        are not modified.


        :param connector_id:
        :param auth: Authentication configuration for a connector instance
        :param sync: Synchronization configuration for a connector instance
        :param filters: Filter configuration to control what data is synced (sync filters and indexing filters)
        :param base_url: Base URL for self-hosted instances
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url_ = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url_ = server_url
        else:
            base_url_ = self._get_url(base_url_, url_variables)

        request = models.UpdateConnectorConfigRequestRequest(
            connector_id=connector_id,
            body=models.UpdateConnectorConfigRequest(
                auth=utils.get_pydantic_model(
                    auth, Optional[models.ConnectorAuthConfig]
                ),
                sync=utils.get_pydantic_model(
                    sync, Optional[models.ConnectorSyncConfig]
                ),
                filters=utils.get_pydantic_model(
                    filters, Optional[models.ConnectorFiltersConfig]
                ),
                base_url=base_url,
            ),
        )

        req = self._build_request_async(
            method="PUT",
            path="/connectors/{connectorId}/config",
            base_url=base_url_,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.UpdateConnectorConfigRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url_ or "",
                operation_id="updateConnectorConfig",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.UpdateConnectorConfigResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def update_auth_config(
        self,
        *,
        connector_id: str,
        auth: Union[models.ConnectorAuthConfig, models.ConnectorAuthConfigTypedDict],
        base_url: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateConnectorAuthConfigResponse:
        r"""Update authentication configuration

        Update only the authentication configuration.<br><br>
        <b>Use Case:</b><br>
        Use this when you need to update credentials without changing
        sync or filter settings. Useful for credential rotation.<br><br>
        <b>Prerequisites:</b><br>
        Connector must be disabled. This endpoint clears OAuth state,
        requiring re-authentication for OAuth connectors.


        :param connector_id:
        :param auth: Authentication configuration for a connector instance
        :param base_url: Base URL (if changed with auth update)
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url_ = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url_ = server_url
        else:
            base_url_ = self._get_url(base_url_, url_variables)

        request = models.UpdateConnectorAuthConfigRequest(
            connector_id=connector_id,
            body=models.UpdateConnectorAuthRequest(
                auth=utils.get_pydantic_model(auth, models.ConnectorAuthConfig),
                base_url=base_url,
            ),
        )

        req = self._build_request(
            method="PUT",
            path="/connectors/{connectorId}/config/auth",
            base_url=base_url_,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.UpdateConnectorAuthRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url_ or "",
                operation_id="updateConnectorAuthConfig",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.UpdateConnectorAuthConfigResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def update_auth_config_async(
        self,
        *,
        connector_id: str,
        auth: Union[models.ConnectorAuthConfig, models.ConnectorAuthConfigTypedDict],
        base_url: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateConnectorAuthConfigResponse:
        r"""Update authentication configuration

        Update only the authentication configuration.<br><br>
        <b>Use Case:</b><br>
        Use this when you need to update credentials without changing
        sync or filter settings. Useful for credential rotation.<br><br>
        <b>Prerequisites:</b><br>
        Connector must be disabled. This endpoint clears OAuth state,
        requiring re-authentication for OAuth connectors.


        :param connector_id:
        :param auth: Authentication configuration for a connector instance
        :param base_url: Base URL (if changed with auth update)
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url_ = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url_ = server_url
        else:
            base_url_ = self._get_url(base_url_, url_variables)

        request = models.UpdateConnectorAuthConfigRequest(
            connector_id=connector_id,
            body=models.UpdateConnectorAuthRequest(
                auth=utils.get_pydantic_model(auth, models.ConnectorAuthConfig),
                base_url=base_url,
            ),
        )

        req = self._build_request_async(
            method="PUT",
            path="/connectors/{connectorId}/config/auth",
            base_url=base_url_,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.UpdateConnectorAuthRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url_ or "",
                operation_id="updateConnectorAuthConfig",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.UpdateConnectorAuthConfigResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def get_google_workspace_credentials(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GoogleWorkspaceCredentials:
        r"""Get Google Workspace credentials status

        Check if Google Workspace credentials are configured.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/configurationManager/connectors/googleWorkspaceCredentials",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getGoogleWorkspaceCredentials",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GoogleWorkspaceCredentials, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def get_google_workspace_credentials_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GoogleWorkspaceCredentials:
        r"""Get Google Workspace credentials status

        Check if Google Workspace credentials are configured.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/configurationManager/connectors/googleWorkspaceCredentials",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getGoogleWorkspaceCredentials",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GoogleWorkspaceCredentials, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
