"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from pipeshub import errors, models, utils
from pipeshub._hooks import HookContext
from pipeshub.types import OptionalNullable, UNSET
from pipeshub.utils import get_security_from_env
from pipeshub.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Mapping, Optional


class OauthProvider(BaseSDK):
    def authorize(
        self,
        *,
        response_type: models.ResponseType,
        client_id: str,
        redirect_uri: str,
        scope: str,
        state: str,
        code_challenge: Optional[str] = None,
        code_challenge_method: Optional[
            models.OauthAuthorizeCodeChallengeMethod
        ] = None,
        nonce: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OauthAuthorizeResponse:
        r"""Initiate OAuth authorization flow

        OAuth 2.0 Authorization Endpoint (RFC 6749 Section 4.1.1).
        <br><br>
        Initiates the authorization code flow. Users are redirected here by OAuth clients
        to authorize access to their account.
        <br><br>
        <b>Flow:</b><br>
        1. Client redirects user to this endpoint with required parameters<br>
        2. If not logged in, user is redirected to PipesHub login<br>
        3. User sees consent page with requested scopes<br>
        4. User grants or denies consent<br>
        5. User is redirected back to client with authorization code
        <br><br>
        <b>PKCE Support (RFC 7636):</b><br>
        - Required for public clients (SPA, mobile apps)<br>
        - Recommended for confidential clients<br>
        - Use S256 method (SHA256 hash of code_verifier)
        <br><br>
        <b>Security:</b><br>
        - Always use HTTPS in production<br>
        - State parameter provides CSRF protection<br>
        - Redirect URI must match registered URIs exactly


        :param response_type: Must be \"code\" for authorization code grant
        :param client_id: OAuth app client ID
        :param redirect_uri: Callback URI (must match registered URI)
        :param scope: Space-separated list of requested scopes
        :param state: Random string for CSRF protection
        :param code_challenge: PKCE code challenge (base64url-encoded)
        :param code_challenge_method: PKCE method (S256 recommended)
        :param nonce: Nonce for ID token binding
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OauthAuthorizeRequest(
            response_type=response_type,
            client_id=client_id,
            redirect_uri=redirect_uri,
            scope=scope,
            state=state,
            code_challenge=code_challenge,
            code_challenge_method=code_challenge_method,
            nonce=nonce,
        )

        req = self._build_request(
            method="GET",
            path="/oauth/authorize",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthAuthorize",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "302", "*"):
            return models.OauthAuthorizeResponse(
                headers=utils.get_response_headers(http_res.headers)
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def authorize_async(
        self,
        *,
        response_type: models.ResponseType,
        client_id: str,
        redirect_uri: str,
        scope: str,
        state: str,
        code_challenge: Optional[str] = None,
        code_challenge_method: Optional[
            models.OauthAuthorizeCodeChallengeMethod
        ] = None,
        nonce: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OauthAuthorizeResponse:
        r"""Initiate OAuth authorization flow

        OAuth 2.0 Authorization Endpoint (RFC 6749 Section 4.1.1).
        <br><br>
        Initiates the authorization code flow. Users are redirected here by OAuth clients
        to authorize access to their account.
        <br><br>
        <b>Flow:</b><br>
        1. Client redirects user to this endpoint with required parameters<br>
        2. If not logged in, user is redirected to PipesHub login<br>
        3. User sees consent page with requested scopes<br>
        4. User grants or denies consent<br>
        5. User is redirected back to client with authorization code
        <br><br>
        <b>PKCE Support (RFC 7636):</b><br>
        - Required for public clients (SPA, mobile apps)<br>
        - Recommended for confidential clients<br>
        - Use S256 method (SHA256 hash of code_verifier)
        <br><br>
        <b>Security:</b><br>
        - Always use HTTPS in production<br>
        - State parameter provides CSRF protection<br>
        - Redirect URI must match registered URIs exactly


        :param response_type: Must be \"code\" for authorization code grant
        :param client_id: OAuth app client ID
        :param redirect_uri: Callback URI (must match registered URI)
        :param scope: Space-separated list of requested scopes
        :param state: Random string for CSRF protection
        :param code_challenge: PKCE code challenge (base64url-encoded)
        :param code_challenge_method: PKCE method (S256 recommended)
        :param nonce: Nonce for ID token binding
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OauthAuthorizeRequest(
            response_type=response_type,
            client_id=client_id,
            redirect_uri=redirect_uri,
            scope=scope,
            state=state,
            code_challenge=code_challenge,
            code_challenge_method=code_challenge_method,
            nonce=nonce,
        )

        req = self._build_request_async(
            method="GET",
            path="/oauth/authorize",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthAuthorize",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "302", "*"):
            return models.OauthAuthorizeResponse(
                headers=utils.get_response_headers(http_res.headers)
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def submit_consent(
        self,
        *,
        client_id: str,
        redirect_uri: str,
        scope: str,
        state: str,
        consent: models.Consent,
        code_challenge: Optional[str] = None,
        code_challenge_method: Optional[models.CodeChallengeMethod] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OauthAuthorizeConsentResponse:
        r"""Submit authorization consent

        Submit user's consent decision for OAuth authorization.
        <br><br>
        Called after user reviews the consent page and makes a decision.
        This endpoint generates an authorization code if consent is granted.
        <br><br>
        <b>Responses:</b><br>
        - Consent granted: Redirects to client with authorization code<br>
        - Consent denied: Redirects to client with `access_denied` error


        :param client_id: The OAuth app's client ID
        :param redirect_uri: Redirect URI (must match authorization request)
        :param scope: Requested scopes
        :param state: State parameter from authorization request
        :param consent: User's consent decision
        :param code_challenge: PKCE code challenge (if used in authorization request)
        :param code_challenge_method: PKCE challenge method
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthConsentRequest(
            client_id=client_id,
            redirect_uri=redirect_uri,
            scope=scope,
            state=state,
            consent=consent,
            code_challenge=code_challenge,
            code_challenge_method=code_challenge_method,
        )

        req = self._build_request(
            method="POST",
            path="/oauth/authorize",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthConsentRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthAuthorizeConsent",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.OauthAuthorizeConsentResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def submit_consent_async(
        self,
        *,
        client_id: str,
        redirect_uri: str,
        scope: str,
        state: str,
        consent: models.Consent,
        code_challenge: Optional[str] = None,
        code_challenge_method: Optional[models.CodeChallengeMethod] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OauthAuthorizeConsentResponse:
        r"""Submit authorization consent

        Submit user's consent decision for OAuth authorization.
        <br><br>
        Called after user reviews the consent page and makes a decision.
        This endpoint generates an authorization code if consent is granted.
        <br><br>
        <b>Responses:</b><br>
        - Consent granted: Redirects to client with authorization code<br>
        - Consent denied: Redirects to client with `access_denied` error


        :param client_id: The OAuth app's client ID
        :param redirect_uri: Redirect URI (must match authorization request)
        :param scope: Requested scopes
        :param state: State parameter from authorization request
        :param consent: User's consent decision
        :param code_challenge: PKCE code challenge (if used in authorization request)
        :param code_challenge_method: PKCE challenge method
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthConsentRequest(
            client_id=client_id,
            redirect_uri=redirect_uri,
            scope=scope,
            state=state,
            consent=consent,
            code_challenge=code_challenge,
            code_challenge_method=code_challenge_method,
        )

        req = self._build_request_async(
            method="POST",
            path="/oauth/authorize",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthConsentRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthAuthorizeConsent",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.OauthAuthorizeConsentResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def exchange_token(
        self,
        *,
        grant_type: models.GrantType,
        code: Optional[str] = None,
        redirect_uri: Optional[str] = None,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        refresh_token: Optional[str] = None,
        scope: Optional[str] = None,
        code_verifier: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OAuthTokenResponse:
        r"""Exchange authorization code for tokens

        OAuth 2.0 Token Endpoint (RFC 6749 Section 4.1.3).
        <br><br>
        Exchanges an authorization code, client credentials, or refresh token for access tokens.
        <br><br>
        <b>Grant Types:</b><br>
        - `authorization_code`: Exchange auth code for tokens (user-based)<br>
        - `client_credentials`: Get tokens for machine-to-machine auth<br>
        - `refresh_token`: Get new access token using refresh token
        <br><br>
        <b>Client Authentication:</b><br>
        Can be provided via:<br>
        - HTTP Basic auth: `Authorization: Basic base64(client_id:client_secret)`<br>
        - Request body: `client_id` and `client_secret` parameters
        <br><br>
        <b>PKCE Verification:</b><br>
        If authorization used PKCE, the `code_verifier` must be provided and will be
        verified against the stored code challenge.


        :param grant_type: OAuth grant type:
            - `authorization_code`: Exchange auth code for tokens
            - `client_credentials`: Machine-to-machine auth
            - `refresh_token`: Get new access token using refresh token

        :param code: Authorization code (required for authorization_code grant)
        :param redirect_uri: Redirect URI (required for authorization_code grant)
        :param client_id: Client ID (can also be sent via Basic auth header)
        :param client_secret: Client secret (can also be sent via Basic auth header)
        :param refresh_token: Refresh token (required for refresh_token grant)
        :param scope: Requested scopes (optional, defaults to original grant scopes)
        :param code_verifier: PKCE code verifier (RFC 7636). Required if code_challenge was used.
            Must be 43-128 characters from [A-Za-z0-9-._~]

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthTokenRequest(
            grant_type=grant_type,
            code=code,
            redirect_uri=redirect_uri,
            client_id=client_id,
            client_secret=client_secret,
            refresh_token=refresh_token,
            scope=scope,
            code_verifier=code_verifier,
        )

        req = self._build_request(
            method="POST",
            path="/oauth/token",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthTokenRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthToken",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.OAuthTokenResponse, http_res)
        if utils.match_response(http_res, ["400", "401"], "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def exchange_token_async(
        self,
        *,
        grant_type: models.GrantType,
        code: Optional[str] = None,
        redirect_uri: Optional[str] = None,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        refresh_token: Optional[str] = None,
        scope: Optional[str] = None,
        code_verifier: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OAuthTokenResponse:
        r"""Exchange authorization code for tokens

        OAuth 2.0 Token Endpoint (RFC 6749 Section 4.1.3).
        <br><br>
        Exchanges an authorization code, client credentials, or refresh token for access tokens.
        <br><br>
        <b>Grant Types:</b><br>
        - `authorization_code`: Exchange auth code for tokens (user-based)<br>
        - `client_credentials`: Get tokens for machine-to-machine auth<br>
        - `refresh_token`: Get new access token using refresh token
        <br><br>
        <b>Client Authentication:</b><br>
        Can be provided via:<br>
        - HTTP Basic auth: `Authorization: Basic base64(client_id:client_secret)`<br>
        - Request body: `client_id` and `client_secret` parameters
        <br><br>
        <b>PKCE Verification:</b><br>
        If authorization used PKCE, the `code_verifier` must be provided and will be
        verified against the stored code challenge.


        :param grant_type: OAuth grant type:
            - `authorization_code`: Exchange auth code for tokens
            - `client_credentials`: Machine-to-machine auth
            - `refresh_token`: Get new access token using refresh token

        :param code: Authorization code (required for authorization_code grant)
        :param redirect_uri: Redirect URI (required for authorization_code grant)
        :param client_id: Client ID (can also be sent via Basic auth header)
        :param client_secret: Client secret (can also be sent via Basic auth header)
        :param refresh_token: Refresh token (required for refresh_token grant)
        :param scope: Requested scopes (optional, defaults to original grant scopes)
        :param code_verifier: PKCE code verifier (RFC 7636). Required if code_challenge was used.
            Must be 43-128 characters from [A-Za-z0-9-._~]

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthTokenRequest(
            grant_type=grant_type,
            code=code,
            redirect_uri=redirect_uri,
            client_id=client_id,
            client_secret=client_secret,
            refresh_token=refresh_token,
            scope=scope,
            code_verifier=code_verifier,
        )

        req = self._build_request_async(
            method="POST",
            path="/oauth/token",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthTokenRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthToken",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.OAuthTokenResponse, http_res)
        if utils.match_response(http_res, ["400", "401"], "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def revoke(
        self,
        *,
        token: str,
        client_id: str,
        token_type_hint: Optional[models.OAuthRevokeRequestTokenTypeHint] = None,
        client_secret: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Revoke an access or refresh token

        OAuth 2.0 Token Revocation Endpoint (RFC 7009).
        <br><br>
        Revokes an access token or refresh token, preventing further use.
        Revoking a refresh token also invalidates associated access tokens.
        <br><br>
        <b>Use Cases:</b><br>
        - User logs out of third-party app<br>
        - User revokes app access from account settings<br>
        - Security incident response
        <br><br>
        <b>Note:</b> Returns 200 OK even if token was already revoked or invalid
        (per RFC 7009, to prevent token enumeration).


        :param token: The token to revoke
        :param client_id: Client ID
        :param token_type_hint: Hint about token type (optional, improves performance)
        :param client_secret: Client secret
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthRevokeRequest(
            token=token,
            token_type_hint=token_type_hint,
            client_id=client_id,
            client_secret=client_secret,
        )

        req = self._build_request(
            method="POST",
            path="/oauth/revoke",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthRevokeRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthRevoke",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "*"):
            return
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def revoke_async(
        self,
        *,
        token: str,
        client_id: str,
        token_type_hint: Optional[models.OAuthRevokeRequestTokenTypeHint] = None,
        client_secret: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Revoke an access or refresh token

        OAuth 2.0 Token Revocation Endpoint (RFC 7009).
        <br><br>
        Revokes an access token or refresh token, preventing further use.
        Revoking a refresh token also invalidates associated access tokens.
        <br><br>
        <b>Use Cases:</b><br>
        - User logs out of third-party app<br>
        - User revokes app access from account settings<br>
        - Security incident response
        <br><br>
        <b>Note:</b> Returns 200 OK even if token was already revoked or invalid
        (per RFC 7009, to prevent token enumeration).


        :param token: The token to revoke
        :param client_id: Client ID
        :param token_type_hint: Hint about token type (optional, improves performance)
        :param client_secret: Client secret
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthRevokeRequest(
            token=token,
            token_type_hint=token_type_hint,
            client_id=client_id,
            client_secret=client_secret,
        )

        req = self._build_request_async(
            method="POST",
            path="/oauth/revoke",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthRevokeRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthRevoke",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "*"):
            return
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def introspect(
        self,
        *,
        token: str,
        client_id: str,
        token_type_hint: Optional[models.OAuthIntrospectRequestTokenTypeHint] = None,
        client_secret: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OAuthIntrospectResponse:
        r"""Introspect a token

        OAuth 2.0 Token Introspection Endpoint (RFC 7662).
        <br><br>
        Check if a token is active and retrieve its metadata.
        <br><br>
        <b>Use Cases:</b><br>
        - Resource servers validating tokens<br>
        - Debugging token issues<br>
        - Checking token scopes before processing requests
        <br><br>
        <b>Response:</b><br>
        - Active token: Returns `active: true` with token metadata<br>
        - Invalid/expired/revoked token: Returns only `active: false`


        :param token: The token to introspect
        :param client_id: Client ID
        :param token_type_hint: Hint about token type
        :param client_secret: Client secret
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthIntrospectRequest(
            token=token,
            token_type_hint=token_type_hint,
            client_id=client_id,
            client_secret=client_secret,
        )

        req = self._build_request(
            method="POST",
            path="/oauth/introspect",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthIntrospectRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthIntrospect",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.OAuthIntrospectResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def introspect_async(
        self,
        *,
        token: str,
        client_id: str,
        token_type_hint: Optional[models.OAuthIntrospectRequestTokenTypeHint] = None,
        client_secret: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.OAuthIntrospectResponse:
        r"""Introspect a token

        OAuth 2.0 Token Introspection Endpoint (RFC 7662).
        <br><br>
        Check if a token is active and retrieve its metadata.
        <br><br>
        <b>Use Cases:</b><br>
        - Resource servers validating tokens<br>
        - Debugging token issues<br>
        - Checking token scopes before processing requests
        <br><br>
        <b>Response:</b><br>
        - Active token: Returns `active: true` with token metadata<br>
        - Invalid/expired/revoked token: Returns only `active: false`


        :param token: The token to introspect
        :param client_id: Client ID
        :param token_type_hint: Hint about token type
        :param client_secret: Client secret
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OAuthIntrospectRequest(
            token=token,
            token_type_hint=token_type_hint,
            client_id=client_id,
            client_secret=client_secret,
        )

        req = self._build_request_async(
            method="POST",
            path="/oauth/introspect",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.OAuthIntrospectRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="oauthIntrospect",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.OAuthIntrospectResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.OAuthErrorResponseData, http_res
            )
            raise errors.OAuthErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
