"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from pipeshub import errors, models, utils
from pipeshub._hooks import HookContext
from pipeshub.types import BaseModel, OptionalNullable, UNSET
from pipeshub.utils import get_security_from_env
from pipeshub.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Mapping, Optional, Union, cast


class Saml(BaseSDK):
    def sign_in(
        self,
        *,
        email: str,
        session_token: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SignInViaSAMLResponse:
        r"""Initiate SAML sign-in flow

        Initiate SAML Single Sign-On authentication by redirecting to the Identity Provider (IDP).
        <br><br>
        <b>Usage:</b><br>
        1. Call <code>/userAccount/initAuth</code> to get a session token<br>
        2. If <code>samlSso</code> is in the allowed methods, redirect the user to this endpoint<br>
        3. User authenticates with their IDP<br>
        4. IDP redirects back to <code>/saml/signIn/callback</code> with SAML response<br>
        5. Callback completes authentication and returns tokens
        <br><br>
        <b>Note:</b> This is a browser redirect endpoint, not a typical API call.
        The user's browser should be redirected to this URL.
        <br><br>
        <b>Prerequisites:</b><br>
        - Organization must have SAML SSO configured via <code>/saml/updateAppConfig</code><br>
        - User must belong to an organization with SAML enabled


        :param email: User's email address
        :param session_token: Session token from `/userAccount/initAuth`. Optional but recommended
            for maintaining authentication state across the SAML flow.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SignInViaSAMLRequest(
            email=email,
            session_token=session_token,
        )

        req = self._build_request(
            method="GET",
            path="/saml/signIn",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="*/*",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="signInViaSAML",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "302", "*"):
            return models.SignInViaSAMLResponse(
                headers=utils.get_response_headers(http_res.headers)
            )
        if utils.match_response(http_res, ["400", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def sign_in_async(
        self,
        *,
        email: str,
        session_token: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SignInViaSAMLResponse:
        r"""Initiate SAML sign-in flow

        Initiate SAML Single Sign-On authentication by redirecting to the Identity Provider (IDP).
        <br><br>
        <b>Usage:</b><br>
        1. Call <code>/userAccount/initAuth</code> to get a session token<br>
        2. If <code>samlSso</code> is in the allowed methods, redirect the user to this endpoint<br>
        3. User authenticates with their IDP<br>
        4. IDP redirects back to <code>/saml/signIn/callback</code> with SAML response<br>
        5. Callback completes authentication and returns tokens
        <br><br>
        <b>Note:</b> This is a browser redirect endpoint, not a typical API call.
        The user's browser should be redirected to this URL.
        <br><br>
        <b>Prerequisites:</b><br>
        - Organization must have SAML SSO configured via <code>/saml/updateAppConfig</code><br>
        - User must belong to an organization with SAML enabled


        :param email: User's email address
        :param session_token: Session token from `/userAccount/initAuth`. Optional but recommended
            for maintaining authentication state across the SAML flow.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SignInViaSAMLRequest(
            email=email,
            session_token=session_token,
        )

        req = self._build_request_async(
            method="GET",
            path="/saml/signIn",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="*/*",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="signInViaSAML",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "302", "*"):
            return models.SignInViaSAMLResponse(
                headers=utils.get_response_headers(http_res.headers)
            )
        if utils.match_response(http_res, ["400", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def callback(
        self,
        *,
        request: Optional[
            Union[models.SamlCallbackRequest, models.SamlCallbackRequestTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SamlCallbackResponse:
        r"""SAML authentication callback

        Handle the callback from SAML Identity Provider after user authentication.
        This endpoint processes the SAML response and completes the authentication flow.
        <br><br>
        <b>Note:</b> This endpoint is called by the IDP, not directly by the client.
        The IDP posts the SAML response to this URL after user authentication.
        <br><br>
        <b>Flow:</b><br>
        1. IDP posts SAMLResponse and RelayState<br>
        2. Server validates SAML assertion signature<br>
        3. Server extracts user identity from assertion<br>
        4. Server completes the authentication step<br>
        5. Redirects to frontend with success/error status
        <br><br>
        <b>RelayState:</b> Contains the session token to resume the authentication flow.


        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, Optional[models.SamlCallbackRequest])
        request = cast(Optional[models.SamlCallbackRequest], request)

        req = self._build_request(
            method="POST",
            path="/saml/signIn/callback",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, True, "form", Optional[models.SamlCallbackRequest]
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="samlCallback",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "302", "*"):
            return models.SamlCallbackResponse(
                headers=utils.get_response_headers(http_res.headers)
            )
        if utils.match_response(http_res, ["400", "401"], "application/json"):
            response_data = unmarshal_json_response(errors.AuthErrorData, http_res)
            raise errors.AuthError(response_data, http_res)
        if utils.match_response(http_res, ["404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def callback_async(
        self,
        *,
        request: Optional[
            Union[models.SamlCallbackRequest, models.SamlCallbackRequestTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SamlCallbackResponse:
        r"""SAML authentication callback

        Handle the callback from SAML Identity Provider after user authentication.
        This endpoint processes the SAML response and completes the authentication flow.
        <br><br>
        <b>Note:</b> This endpoint is called by the IDP, not directly by the client.
        The IDP posts the SAML response to this URL after user authentication.
        <br><br>
        <b>Flow:</b><br>
        1. IDP posts SAMLResponse and RelayState<br>
        2. Server validates SAML assertion signature<br>
        3. Server extracts user identity from assertion<br>
        4. Server completes the authentication step<br>
        5. Redirects to frontend with success/error status
        <br><br>
        <b>RelayState:</b> Contains the session token to resume the authentication flow.


        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, Optional[models.SamlCallbackRequest])
        request = cast(Optional[models.SamlCallbackRequest], request)

        req = self._build_request_async(
            method="POST",
            path="/saml/signIn/callback",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, True, "form", Optional[models.SamlCallbackRequest]
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="samlCallback",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "401", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "302", "*"):
            return models.SamlCallbackResponse(
                headers=utils.get_response_headers(http_res.headers)
            )
        if utils.match_response(http_res, ["400", "401"], "application/json"):
            response_data = unmarshal_json_response(errors.AuthErrorData, http_res)
            raise errors.AuthError(response_data, http_res)
        if utils.match_response(http_res, ["404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def update_app_config(
        self,
        *,
        security: Union[
            models.UpdateSamlAppConfigSecurity,
            models.UpdateSamlAppConfigSecurityTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateSamlAppConfigResponse:
        r"""Reload SAML application configuration (Internal)

        Internal endpoint to reload SAML configuration from the configuration manager.
        This is called by other services when SAML settings are updated.<br><br>
        <b>Purpose:</b><br>
        When SAML configuration is updated in the Configuration Manager, this endpoint
        is called to reload the settings into the authentication service without restart.<br><br>
        <b>Effects:</b><br>
        <ul>
        <li>Reloads AppConfig from configuration files</li>
        <li>Rebinds authentication controllers with new config</li>
        <li>Updates SAML passport strategy settings</li>
        </ul>
        <b>Note:</b> This is an internal service-to-service endpoint.


        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="POST",
            path="/saml/updateAppConfig",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=utils.get_pydantic_model(
                security, models.UpdateSamlAppConfigSecurity
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="updateSamlAppConfig",
                oauth2_scopes=None,
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UpdateSamlAppConfigResponse, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def update_app_config_async(
        self,
        *,
        security: Union[
            models.UpdateSamlAppConfigSecurity,
            models.UpdateSamlAppConfigSecurityTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UpdateSamlAppConfigResponse:
        r"""Reload SAML application configuration (Internal)

        Internal endpoint to reload SAML configuration from the configuration manager.
        This is called by other services when SAML settings are updated.<br><br>
        <b>Purpose:</b><br>
        When SAML configuration is updated in the Configuration Manager, this endpoint
        is called to reload the settings into the authentication service without restart.<br><br>
        <b>Effects:</b><br>
        <ul>
        <li>Reloads AppConfig from configuration files</li>
        <li>Rebinds authentication controllers with new config</li>
        <li>Updates SAML passport strategy settings</li>
        </ul>
        <b>Note:</b> This is an internal service-to-service endpoint.


        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="POST",
            path="/saml/updateAppConfig",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=utils.get_pydantic_model(
                security, models.UpdateSamlAppConfigSecurity
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="updateSamlAppConfig",
                oauth2_scopes=None,
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UpdateSamlAppConfigResponse, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
