"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from pipeshub import errors, models, utils
from pipeshub._hooks import HookContext
from pipeshub.types import OptionalNullable, UNSET
from pipeshub.utils import get_security_from_env
from pipeshub.utils.unmarshal_json_response import unmarshal_json_response
from typing import List, Mapping, Optional, Union


class Upload(BaseSDK):
    r"""File upload operations"""

    def to_knowledge_base(
        self,
        *,
        kb_id: str,
        files: Union[
            List[models.UploadRecordsToKBFile],
            List[models.UploadRecordsToKBFileTypedDict],
        ],
        files_metadata: Optional[str] = None,
        is_versioned: Optional[bool] = True,
        record_type: Optional[str] = "FILE",
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UploadResult:
        r"""Upload files to knowledge base

        Upload one or more files directly to a knowledge base.<br><br>
        <b>Overview:</b><br>
        Batch upload multiple files in a single request. Each file becomes a new record in the KB with automatic content indexing.<br><br>
        <b>Upload Limits:</b><br>
        <ul>
        <li><b>Max files per request:</b> 1000</li>
        <li><b>Default max file size:</b> 30MB (configurable via platform settings)</li>
        <li>Use <code>GET /knowledgeBase/limits</code> to check current limits</li>
        </ul>
        <b>Supported File Types:</b><br>
        Documents (PDF, DOCX, TXT), Images (PNG, JPG), Videos (MP4), and more.<br><br>
        <b>File Metadata:</b><br>
        Use <code>files_metadata</code> to provide additional info like file paths and last modified timestamps.<br><br>
        <b>Versioning:</b><br>
        Set <code>isVersioned: true</code> to enable version tracking for uploaded files.


        :param kb_id: Knowledge base ID
        :param files: Files to upload (max 1000)
        :param files_metadata: JSON array with file_path and last_modified for each file
        :param is_versioned: Enable version tracking
        :param record_type: Type of records to create
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UploadRecordsToKBRequest(
            kb_id=kb_id,
            body=models.UploadRecordsToKBRequestBody(
                files=utils.get_pydantic_model(
                    files, List[models.UploadRecordsToKBFile]
                ),
                files_metadata=files_metadata,
                is_versioned=is_versioned,
                record_type=record_type,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/knowledgeBase/{kbId}/upload",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "multipart",
                models.UploadRecordsToKBRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="uploadRecordsToKB",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "413", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UploadResult, http_res)
        if utils.match_response(
            http_res, ["400", "401", "403", "404", "413", "4XX"], "*"
        ):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def to_knowledge_base_async(
        self,
        *,
        kb_id: str,
        files: Union[
            List[models.UploadRecordsToKBFile],
            List[models.UploadRecordsToKBFileTypedDict],
        ],
        files_metadata: Optional[str] = None,
        is_versioned: Optional[bool] = True,
        record_type: Optional[str] = "FILE",
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UploadResult:
        r"""Upload files to knowledge base

        Upload one or more files directly to a knowledge base.<br><br>
        <b>Overview:</b><br>
        Batch upload multiple files in a single request. Each file becomes a new record in the KB with automatic content indexing.<br><br>
        <b>Upload Limits:</b><br>
        <ul>
        <li><b>Max files per request:</b> 1000</li>
        <li><b>Default max file size:</b> 30MB (configurable via platform settings)</li>
        <li>Use <code>GET /knowledgeBase/limits</code> to check current limits</li>
        </ul>
        <b>Supported File Types:</b><br>
        Documents (PDF, DOCX, TXT), Images (PNG, JPG), Videos (MP4), and more.<br><br>
        <b>File Metadata:</b><br>
        Use <code>files_metadata</code> to provide additional info like file paths and last modified timestamps.<br><br>
        <b>Versioning:</b><br>
        Set <code>isVersioned: true</code> to enable version tracking for uploaded files.


        :param kb_id: Knowledge base ID
        :param files: Files to upload (max 1000)
        :param files_metadata: JSON array with file_path and last_modified for each file
        :param is_versioned: Enable version tracking
        :param record_type: Type of records to create
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UploadRecordsToKBRequest(
            kb_id=kb_id,
            body=models.UploadRecordsToKBRequestBody(
                files=utils.get_pydantic_model(
                    files, List[models.UploadRecordsToKBFile]
                ),
                files_metadata=files_metadata,
                is_versioned=is_versioned,
                record_type=record_type,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/knowledgeBase/{kbId}/upload",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "multipart",
                models.UploadRecordsToKBRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="uploadRecordsToKB",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "413", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UploadResult, http_res)
        if utils.match_response(
            http_res, ["400", "401", "403", "404", "413", "4XX"], "*"
        ):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def records_to_folder(
        self,
        *,
        kb_id: str,
        folder_id: str,
        files: Union[
            List[models.UploadRecordsToFolderFile],
            List[models.UploadRecordsToFolderFileTypedDict],
        ],
        files_metadata: Optional[str] = None,
        is_versioned: Optional[bool] = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UploadResult:
        r"""Upload files to folder

        Upload files directly to a specific folder within a knowledge base.<br><br>
        <b>Same as KB upload</b> but files are placed in the specified folder instead of KB root.


        :param kb_id:
        :param folder_id: Target folder ID
        :param files:
        :param files_metadata: JSON array with file metadata
        :param is_versioned:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UploadRecordsToFolderRequest(
            kb_id=kb_id,
            folder_id=folder_id,
            body=models.UploadRecordsToFolderRequestBody(
                files=utils.get_pydantic_model(
                    files, List[models.UploadRecordsToFolderFile]
                ),
                files_metadata=files_metadata,
                is_versioned=is_versioned,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/knowledgeBase/{kbId}/folder/{folderId}/upload",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "multipart",
                models.UploadRecordsToFolderRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="uploadRecordsToFolder",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UploadResult, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def records_to_folder_async(
        self,
        *,
        kb_id: str,
        folder_id: str,
        files: Union[
            List[models.UploadRecordsToFolderFile],
            List[models.UploadRecordsToFolderFileTypedDict],
        ],
        files_metadata: Optional[str] = None,
        is_versioned: Optional[bool] = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UploadResult:
        r"""Upload files to folder

        Upload files directly to a specific folder within a knowledge base.<br><br>
        <b>Same as KB upload</b> but files are placed in the specified folder instead of KB root.


        :param kb_id:
        :param folder_id: Target folder ID
        :param files:
        :param files_metadata: JSON array with file metadata
        :param is_versioned:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UploadRecordsToFolderRequest(
            kb_id=kb_id,
            folder_id=folder_id,
            body=models.UploadRecordsToFolderRequestBody(
                files=utils.get_pydantic_model(
                    files, List[models.UploadRecordsToFolderFile]
                ),
                files_metadata=files_metadata,
                is_versioned=is_versioned,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/knowledgeBase/{kbId}/folder/{folderId}/upload",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "multipart",
                models.UploadRecordsToFolderRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="uploadRecordsToFolder",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UploadResult, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
