"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetAtlassianOauthConfigResponseTypedDict(TypedDict):
    r"""Atlassian config retrieved"""

    client_id: str
    client_secret: str


class GetAtlassianOauthConfigResponse(BaseModel):
    r"""Atlassian config retrieved"""

    client_id: Annotated[str, pydantic.Field(alias="clientId")]

    client_secret: Annotated[str, pydantic.Field(alias="clientSecret")]


try:
    GetAtlassianOauthConfigResponse.model_rebuild()
except NameError:
    pass
