"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .folder import Folder, FolderTypedDict
from .record import Record, RecordTypedDict
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GetKBRecordsSortOrder = Literal[
    "asc",
    "desc",
]


class GetKBRecordsRequestTypedDict(TypedDict):
    kb_id: str
    r"""Knowledge base ID"""
    page: NotRequired[int]
    limit: NotRequired[int]
    search: NotRequired[str]
    r"""Search query for record names"""
    record_types: NotRequired[str]
    r"""Filter by record types (comma-separated)"""
    origins: NotRequired[str]
    r"""Filter by origin"""
    indexing_status: NotRequired[str]
    r"""Filter by indexing status"""
    date_from: NotRequired[int]
    r"""Start date filter (Unix timestamp)"""
    date_to: NotRequired[int]
    r"""End date filter (Unix timestamp)"""
    sort_by: NotRequired[str]
    sort_order: NotRequired[GetKBRecordsSortOrder]


class GetKBRecordsRequest(BaseModel):
    kb_id: Annotated[
        str,
        pydantic.Field(alias="kbId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Knowledge base ID"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20

    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Search query for record names"""

    record_types: Annotated[
        Optional[str],
        pydantic.Field(alias="recordTypes"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by record types (comma-separated)"""

    origins: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by origin"""

    indexing_status: Annotated[
        Optional[str],
        pydantic.Field(alias="indexingStatus"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by indexing status"""

    date_from: Annotated[
        Optional[int],
        pydantic.Field(alias="dateFrom"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Start date filter (Unix timestamp)"""

    date_to: Annotated[
        Optional[int],
        pydantic.Field(alias="dateTo"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""End date filter (Unix timestamp)"""

    sort_by: Annotated[
        Optional[str],
        pydantic.Field(alias="sortBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "createdAtTimestamp"

    sort_order: Annotated[
        Optional[GetKBRecordsSortOrder],
        pydantic.Field(alias="sortOrder"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "desc"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "page",
                "limit",
                "search",
                "recordTypes",
                "origins",
                "indexingStatus",
                "dateFrom",
                "dateTo",
                "sortBy",
                "sortOrder",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetKBRecordsContainerTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    path: NotRequired[str]
    type: NotRequired[str]
    web_url: NotRequired[str]
    record_group_id: NotRequired[str]


class GetKBRecordsContainer(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    path: Optional[str] = None

    type: Optional[str] = None

    web_url: Annotated[Optional[str], pydantic.Field(alias="webUrl")] = None

    record_group_id: Annotated[Optional[str], pydantic.Field(alias="recordGroupId")] = (
        None
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "path", "type", "webUrl", "recordGroupId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetKBRecordsCountsTypedDict(TypedDict):
    folders: NotRequired[int]
    records: NotRequired[int]
    total_items: NotRequired[int]
    total_folders: NotRequired[int]
    total_records: NotRequired[int]


class GetKBRecordsCounts(BaseModel):
    folders: Optional[int] = None

    records: Optional[int] = None

    total_items: Annotated[Optional[int], pydantic.Field(alias="totalItems")] = None

    total_folders: Annotated[Optional[int], pydantic.Field(alias="totalFolders")] = None

    total_records: Annotated[Optional[int], pydantic.Field(alias="totalRecords")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["folders", "records", "totalItems", "totalFolders", "totalRecords"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetKBRecordsAvailableFiltersTypedDict(TypedDict):
    pass


class GetKBRecordsAvailableFilters(BaseModel):
    pass


class GetKBRecordsUserPermissionTypedDict(TypedDict):
    role: NotRequired[str]
    can_upload: NotRequired[bool]
    can_create_folders: NotRequired[bool]
    can_edit: NotRequired[bool]
    can_delete: NotRequired[bool]
    can_manage_permissions: NotRequired[bool]


class GetKBRecordsUserPermission(BaseModel):
    role: Optional[str] = None

    can_upload: Annotated[Optional[bool], pydantic.Field(alias="canUpload")] = None

    can_create_folders: Annotated[
        Optional[bool], pydantic.Field(alias="canCreateFolders")
    ] = None

    can_edit: Annotated[Optional[bool], pydantic.Field(alias="canEdit")] = None

    can_delete: Annotated[Optional[bool], pydantic.Field(alias="canDelete")] = None

    can_manage_permissions: Annotated[
        Optional[bool], pydantic.Field(alias="canManagePermissions")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "role",
                "canUpload",
                "canCreateFolders",
                "canEdit",
                "canDelete",
                "canManagePermissions",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetKBRecordsPaginationTypedDict(TypedDict):
    page: NotRequired[int]
    limit: NotRequired[int]
    total_items: NotRequired[int]
    total_pages: NotRequired[int]
    has_next: NotRequired[bool]
    has_prev: NotRequired[bool]


class GetKBRecordsPagination(BaseModel):
    page: Optional[int] = None

    limit: Optional[int] = None

    total_items: Annotated[Optional[int], pydantic.Field(alias="totalItems")] = None

    total_pages: Annotated[Optional[int], pydantic.Field(alias="totalPages")] = None

    has_next: Annotated[Optional[bool], pydantic.Field(alias="hasNext")] = None

    has_prev: Annotated[Optional[bool], pydantic.Field(alias="hasPrev")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["page", "limit", "totalItems", "totalPages", "hasNext", "hasPrev"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetKBRecordsFiltersTypedDict(TypedDict):
    r"""Applied and available filters"""


class GetKBRecordsFilters(BaseModel):
    r"""Applied and available filters"""


class GetKBRecordsResponseTypedDict(TypedDict):
    r"""Successful operation"""

    success: NotRequired[bool]
    container: NotRequired[GetKBRecordsContainerTypedDict]
    folders: NotRequired[List[FolderTypedDict]]
    records: NotRequired[List[RecordTypedDict]]
    level: NotRequired[int]
    total_count: NotRequired[int]
    counts: NotRequired[GetKBRecordsCountsTypedDict]
    available_filters: NotRequired[GetKBRecordsAvailableFiltersTypedDict]
    pagination_mode: NotRequired[str]
    user_permission: NotRequired[GetKBRecordsUserPermissionTypedDict]
    pagination: NotRequired[GetKBRecordsPaginationTypedDict]
    filters: NotRequired[GetKBRecordsFiltersTypedDict]
    r"""Applied and available filters"""


class GetKBRecordsResponse(BaseModel):
    r"""Successful operation"""

    success: Optional[bool] = None

    container: Optional[GetKBRecordsContainer] = None

    folders: Optional[List[Folder]] = None

    records: Optional[List[Record]] = None

    level: Optional[int] = None

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None

    counts: Optional[GetKBRecordsCounts] = None

    available_filters: Annotated[
        Optional[GetKBRecordsAvailableFilters], pydantic.Field(alias="availableFilters")
    ] = None

    pagination_mode: Annotated[
        Optional[str], pydantic.Field(alias="paginationMode")
    ] = None

    user_permission: Annotated[
        Optional[GetKBRecordsUserPermission], pydantic.Field(alias="userPermission")
    ] = None

    pagination: Optional[GetKBRecordsPagination] = None

    filters: Optional[GetKBRecordsFilters] = None
    r"""Applied and available filters"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "success",
                "container",
                "folders",
                "records",
                "level",
                "totalCount",
                "counts",
                "availableFilters",
                "paginationMode",
                "userPermission",
                "pagination",
                "filters",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetKBRecordsContainer.model_rebuild()
except NameError:
    pass
try:
    GetKBRecordsCounts.model_rebuild()
except NameError:
    pass
try:
    GetKBRecordsUserPermission.model_rebuild()
except NameError:
    pass
try:
    GetKBRecordsPagination.model_rebuild()
except NameError:
    pass
try:
    GetKBRecordsResponse.model_rebuild()
except NameError:
    pass
