"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetSharePointCredentialsResponseTypedDict(TypedDict):
    r"""SharePoint credentials retrieved"""

    client_id: str
    client_secret: str
    tenant_id: str
    sharepoint_domain: str


class GetSharePointCredentialsResponse(BaseModel):
    r"""SharePoint credentials retrieved"""

    client_id: Annotated[str, pydantic.Field(alias="clientId")]

    client_secret: Annotated[str, pydantic.Field(alias="clientSecret")]

    tenant_id: Annotated[str, pydantic.Field(alias="tenantId")]

    sharepoint_domain: Annotated[str, pydantic.Field(alias="sharepointDomain")]


try:
    GetSharePointCredentialsResponse.model_rebuild()
except NameError:
    pass
