"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetTeamUsersRequestTypedDict(TypedDict):
    team_id: str


class GetTeamUsersRequest(BaseModel):
    team_id: Annotated[
        str,
        pydantic.Field(alias="teamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class GetTeamUsersDataTypedDict(TypedDict):
    pass


class GetTeamUsersData(BaseModel):
    pass


class GetTeamUsersResponseTypedDict(TypedDict):
    r"""Team users retrieved successfully"""

    success: NotRequired[bool]
    data: NotRequired[List[GetTeamUsersDataTypedDict]]


class GetTeamUsersResponse(BaseModel):
    r"""Team users retrieved successfully"""

    success: Optional[bool] = None

    data: Optional[List[GetTeamUsersData]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
