"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HandleToolsetOAuthCallbackRequestTypedDict(TypedDict):
    code: NotRequired[str]
    state: NotRequired[str]
    error: NotRequired[str]
    base_url: NotRequired[str]


class HandleToolsetOAuthCallbackRequest(BaseModel):
    code: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    state: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    error: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    base_url: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "state", "error", "base_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HandleToolsetOAuthCallbackResponseTypedDict(TypedDict):
    r"""OAuth callback handled successfully"""

    redirect_url: NotRequired[str]


class HandleToolsetOAuthCallbackResponse(BaseModel):
    r"""OAuth callback handled successfully"""

    redirect_url: Annotated[Optional[str], pydantic.Field(alias="redirectUrl")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["redirectUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    HandleToolsetOAuthCallbackResponse.model_rebuild()
except NameError:
    pass
