"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .knowledgebase import KnowledgeBase, KnowledgeBaseTypedDict
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ListKnowledgeBasesSortBy = Literal[
    "name",
    "createdAtTimestamp",
    "updatedAtTimestamp",
    "userRole",
]
r"""Field to sort by"""


ListKnowledgeBasesSortOrder = Literal[
    "asc",
    "desc",
]
r"""Sort direction"""


class ListKnowledgeBasesRequestTypedDict(TypedDict):
    page: NotRequired[int]
    r"""Page number (1-indexed)"""
    limit: NotRequired[int]
    r"""Results per page (max 100)"""
    search: NotRequired[str]
    r"""Search query for KB names (max 1000 chars)"""
    permissions: NotRequired[str]
    r"""Filter by permission roles (comma-separated)"""
    sort_by: NotRequired[ListKnowledgeBasesSortBy]
    r"""Field to sort by"""
    sort_order: NotRequired[ListKnowledgeBasesSortOrder]
    r"""Sort direction"""


class ListKnowledgeBasesRequest(BaseModel):
    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number (1-indexed)"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20
    r"""Results per page (max 100)"""

    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Search query for KB names (max 1000 chars)"""

    permissions: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by permission roles (comma-separated)"""

    sort_by: Annotated[
        Optional[ListKnowledgeBasesSortBy],
        pydantic.Field(alias="sortBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "name"
    r"""Field to sort by"""

    sort_order: Annotated[
        Optional[ListKnowledgeBasesSortOrder],
        pydantic.Field(alias="sortOrder"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "asc"
    r"""Sort direction"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["page", "limit", "search", "permissions", "sortBy", "sortOrder"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListKnowledgeBasesPaginationTypedDict(TypedDict):
    page: NotRequired[int]
    r"""Current page number"""
    limit: NotRequired[int]
    r"""Items per page"""
    total_count: NotRequired[int]
    r"""Total number of items"""
    total_pages: NotRequired[int]
    r"""Total number of pages"""
    has_next: NotRequired[bool]
    r"""Whether there is a next page"""
    has_prev: NotRequired[bool]
    r"""Whether there is a previous page"""


class ListKnowledgeBasesPagination(BaseModel):
    page: Optional[int] = None
    r"""Current page number"""

    limit: Optional[int] = None
    r"""Items per page"""

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None
    r"""Total number of items"""

    total_pages: Annotated[Optional[int], pydantic.Field(alias="totalPages")] = None
    r"""Total number of pages"""

    has_next: Annotated[Optional[bool], pydantic.Field(alias="hasNext")] = None
    r"""Whether there is a next page"""

    has_prev: Annotated[Optional[bool], pydantic.Field(alias="hasPrev")] = None
    r"""Whether there is a previous page"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["page", "limit", "totalCount", "totalPages", "hasNext", "hasPrev"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListKnowledgeBasesAppliedTypedDict(TypedDict):
    pass


class ListKnowledgeBasesApplied(BaseModel):
    pass


class ListKnowledgeBasesAvailableTypedDict(TypedDict):
    pass


class ListKnowledgeBasesAvailable(BaseModel):
    pass


class ListKnowledgeBasesFiltersTypedDict(TypedDict):
    r"""Applied and available filters"""

    applied: NotRequired[ListKnowledgeBasesAppliedTypedDict]
    available: NotRequired[ListKnowledgeBasesAvailableTypedDict]


class ListKnowledgeBasesFilters(BaseModel):
    r"""Applied and available filters"""

    applied: Optional[ListKnowledgeBasesApplied] = None

    available: Optional[ListKnowledgeBasesAvailable] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["applied", "available"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListKnowledgeBasesResponseTypedDict(TypedDict):
    r"""Successful operation"""

    knowledge_bases: NotRequired[List[KnowledgeBaseTypedDict]]
    pagination: NotRequired[ListKnowledgeBasesPaginationTypedDict]
    filters: NotRequired[ListKnowledgeBasesFiltersTypedDict]
    r"""Applied and available filters"""


class ListKnowledgeBasesResponse(BaseModel):
    r"""Successful operation"""

    knowledge_bases: Annotated[
        Optional[List[KnowledgeBase]], pydantic.Field(alias="knowledgeBases")
    ] = None

    pagination: Optional[ListKnowledgeBasesPagination] = None

    filters: Optional[ListKnowledgeBasesFilters] = None
    r"""Applied and available filters"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["knowledgeBases", "pagination", "filters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ListKnowledgeBasesPagination.model_rebuild()
except NameError:
    pass
try:
    ListKnowledgeBasesResponse.model_rebuild()
except NameError:
    pass
