"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customscheduleconfig import CustomScheduleConfig, CustomScheduleConfigTypedDict
from .dailyscheduleconfig import DailyScheduleConfig, DailyScheduleConfigTypedDict
from .hourlyscheduleconfig import HourlyScheduleConfig, HourlyScheduleConfigTypedDict
from .monthlyscheduleconfig import MonthlyScheduleConfig, MonthlyScheduleConfigTypedDict
from .oncescheduleconfig import OnceScheduleConfig, OnceScheduleConfigTypedDict
from .weeklyscheduleconfig import WeeklyScheduleConfig, WeeklyScheduleConfigTypedDict
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType


ScheduleConfigTypedDict = TypeAliasType(
    "ScheduleConfigTypedDict",
    Union[
        OnceScheduleConfigTypedDict,
        HourlyScheduleConfigTypedDict,
        DailyScheduleConfigTypedDict,
        CustomScheduleConfigTypedDict,
        WeeklyScheduleConfigTypedDict,
        MonthlyScheduleConfigTypedDict,
    ],
)
r"""Schedule configuration for crawling jobs. The structure varies based on <code>scheduleType</code>.<br><br>
<b>Schedule Type Configurations:</b><br>
<ul>
<li><b>hourly:</b> <code>minute</code>, <code>interval</code> (optional)</li>
<li><b>daily:</b> <code>hour</code>, <code>minute</code></li>
<li><b>weekly:</b> <code>daysOfWeek</code>, <code>hour</code>, <code>minute</code></li>
<li><b>monthly:</b> <code>dayOfMonth</code>, <code>hour</code>, <code>minute</code></li>
<li><b>custom:</b> <code>cronExpression</code>, <code>description</code> (optional)</li>
<li><b>once:</b> <code>scheduledTime</code></li>
</ul>

"""


ScheduleConfig = Annotated[
    Union[
        HourlyScheduleConfig,
        DailyScheduleConfig,
        WeeklyScheduleConfig,
        MonthlyScheduleConfig,
        CustomScheduleConfig,
        OnceScheduleConfig,
    ],
    Field(discriminator="schedule_type"),
]
r"""Schedule configuration for crawling jobs. The structure varies based on <code>scheduleType</code>.<br><br>
<b>Schedule Type Configurations:</b><br>
<ul>
<li><b>hourly:</b> <code>minute</code>, <code>interval</code> (optional)</li>
<li><b>daily:</b> <code>hour</code>, <code>minute</code></li>
<li><b>weekly:</b> <code>daysOfWeek</code>, <code>hour</code>, <code>minute</code></li>
<li><b>monthly:</b> <code>dayOfMonth</code>, <code>hour</code>, <code>minute</code></li>
<li><b>custom:</b> <code>cronExpression</code>, <code>description</code> (optional)</li>
<li><b>once:</b> <code>scheduledTime</code></li>
</ul>

"""
