"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SetMetricsCollectionPushIntervalRequestTypedDict(TypedDict):
    r"""Request payload"""

    push_interval: NotRequired[int]
    r"""Push interval in seconds"""


class SetMetricsCollectionPushIntervalRequest(BaseModel):
    r"""Request payload"""

    push_interval: Annotated[Optional[int], pydantic.Field(alias="pushInterval")] = None
    r"""Push interval in seconds"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pushInterval"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SetMetricsCollectionPushIntervalResponseTypedDict(TypedDict):
    r"""Push interval updated"""

    message: NotRequired[str]


class SetMetricsCollectionPushIntervalResponse(BaseModel):
    r"""Push interval updated"""

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SetMetricsCollectionPushIntervalRequest.model_rebuild()
except NameError:
    pass
