"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userrole import UserRole, UserRoleTypedDict
from datetime import datetime
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TeamTypedDict(TypedDict):
    name: str
    r"""Team name"""
    id: NotRequired[str]
    r"""Unique team identifier"""
    description: NotRequired[str]
    r"""Team description"""
    org_id: NotRequired[str]
    r"""Organization ID"""
    user_roles: NotRequired[List[UserRoleTypedDict]]
    r"""Users and their roles in the team"""
    created_at: NotRequired[datetime]
    r"""Creation timestamp (ISO 8601)"""
    updated_at: NotRequired[datetime]
    r"""Last update timestamp (ISO 8601)"""


class Team(BaseModel):
    name: str
    r"""Team name"""

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = None
    r"""Unique team identifier"""

    description: Optional[str] = None
    r"""Team description"""

    org_id: Annotated[Optional[str], pydantic.Field(alias="orgId")] = None
    r"""Organization ID"""

    user_roles: Annotated[
        Optional[List[UserRole]], pydantic.Field(alias="userRoles")
    ] = None
    r"""Users and their roles in the team"""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None
    r"""Creation timestamp (ISO 8601)"""

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
    r"""Last update timestamp (ISO 8601)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["_id", "description", "orgId", "userRoles", "createdAt", "updatedAt"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Team.model_rebuild()
except NameError:
    pass
