"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateTeamUsersPermissionsRequestBodyTypedDict(TypedDict):
    r"""Request payload"""


class UpdateTeamUsersPermissionsRequestBody(BaseModel):
    r"""Request payload"""


class UpdateTeamUsersPermissionsRequestTypedDict(TypedDict):
    team_id: str
    body: UpdateTeamUsersPermissionsRequestBodyTypedDict
    r"""Request payload"""


class UpdateTeamUsersPermissionsRequest(BaseModel):
    team_id: Annotated[
        str,
        pydantic.Field(alias="teamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        UpdateTeamUsersPermissionsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""


class UpdateTeamUsersPermissionsResponseTypedDict(TypedDict):
    r"""Permissions updated successfully"""

    message: NotRequired[str]


class UpdateTeamUsersPermissionsResponse(BaseModel):
    r"""Permissions updated successfully"""

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
