"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Any, Dict
from typing_extensions import Annotated, TypedDict


class UpdateToolsetOAuthConfigRequestTypedDict(TypedDict):
    toolset_type: str
    oauth_config_id: str
    body: Dict[str, Any]


class UpdateToolsetOAuthConfigRequest(BaseModel):
    toolset_type: Annotated[
        str,
        pydantic.Field(alias="toolsetType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    oauth_config_id: Annotated[
        str,
        pydantic.Field(alias="oauthConfigId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        Dict[str, Any],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
