"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import io
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import (
    FieldMetadata,
    MultipartFormMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UploadNextVersionDocumentFileTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class UploadNextVersionDocumentFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UploadNextVersionDocumentRequestBodyTypedDict(TypedDict):
    file: NotRequired[UploadNextVersionDocumentFileTypedDict]


class UploadNextVersionDocumentRequestBody(BaseModel):
    file: Annotated[
        Optional[UploadNextVersionDocumentFile],
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UploadNextVersionDocumentRequestTypedDict(TypedDict):
    document_id: str
    body: UploadNextVersionDocumentRequestBodyTypedDict


class UploadNextVersionDocumentRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        UploadNextVersionDocumentRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]


class UploadNextVersionDocumentResponseTypedDict(TypedDict):
    r"""New version uploaded successfully"""

    message: NotRequired[str]


class UploadNextVersionDocumentResponse(BaseModel):
    r"""New version uploaded successfully"""

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
